package store

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"maps"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/ladderairport/panel/internal/inboundfill"
	_ "modernc.org/sqlite"
)

// Store is a SQLite-backed persistence layer for the panel.
type Store struct {
	db *sql.DB
	// mu serializes the read-modify-write command-queue transitions
	// (lease/complete) so at-least-once delivery stays consistent on the
	// single-writer SQLite connection.
	mu sync.Mutex
}

// Open opens (or creates) a SQLite database at path and ensures schema + defaults.
func Open(path string) (*Store, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, fmt.Errorf("打开 SQLite 数据库失败：%w", err)
	}
	// Single-writer is typical for panel; keep it simple and reliable.
	db.SetMaxOpenConns(1)
	if _, err := db.Exec(`PRAGMA foreign_keys = ON`); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("启用 SQLite 外键失败：%w", err)
	}

	s := &Store{db: db}
	if err := s.migrate(); err != nil {
		_ = db.Close()
		return nil, err
	}
	if err := s.repairInvalidShadowsocks2022Passwords(); err != nil {
		_ = db.Close()
		return nil, err
	}
	if err := s.ensureDefaultSettings(); err != nil {
		_ = db.Close()
		return nil, err
	}
	return s, nil
}

// repairInvalidShadowsocks2022Passwords migrates credentials generated by
// versions up to v0.9.0. Those versions used a generic URL-safe password for
// every Shadowsocks method, while SS2022 requires a standard Base64 PSK with a
// method-specific minimum length.
func (s *Store) repairInvalidShadowsocks2022Passwords() error {
	rows, err := s.db.Query(`SELECT id, params_json FROM inbounds WHERE protocol = 'shadowsocks'`)
	if err != nil {
		return fmt.Errorf("查询需要修复 PSK 的 Shadowsocks 入站失败：%w", err)
	}
	type record struct {
		id     string
		params map[string]any
	}
	var repairs []record
	for rows.Next() {
		var id, paramsJSON string
		if err := rows.Scan(&id, &paramsJSON); err != nil {
			_ = rows.Close()
			return fmt.Errorf("读取待修复的 Shadowsocks 入站失败：%w", err)
		}
		params := map[string]any{}
		if err := unmarshalJSON(paramsJSON, &params); err != nil {
			_ = rows.Close()
			return fmt.Errorf("解析 Shadowsocks 入站 %s 以修复 PSK 失败：%w", id, err)
		}
		changed, err := inboundfill.RepairShadowsocks2022Password(params)
		if err != nil {
			_ = rows.Close()
			return fmt.Errorf("修复 Shadowsocks 入站 %s 的 PSK 失败：%w", id, err)
		}
		if changed {
			repairs = append(repairs, record{id: id, params: params})
		}
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		return fmt.Errorf("查询需要修复 PSK 的 Shadowsocks 入站失败：%w", err)
	}
	if err := rows.Close(); err != nil {
		return err
	}
	for _, repair := range repairs {
		paramsJSON, err := marshalJSON(repair.params)
		if err != nil {
			return fmt.Errorf("编码已修复的 Shadowsocks 入站 %s 失败：%w", repair.id, err)
		}
		if _, err := s.db.Exec(
			`UPDATE inbounds SET params_json = ?, updated_at_unix = ? WHERE id = ?`,
			paramsJSON, nowUnix(), repair.id,
		); err != nil {
			return fmt.Errorf("保存已修复的 Shadowsocks 入站 %s PSK 失败：%w", repair.id, err)
		}
	}
	return nil
}

// Close closes the underlying database.
func (s *Store) Close() error {
	if s == nil || s.db == nil {
		return nil
	}
	return s.db.Close()
}

func (s *Store) migrate() error {
	stmts := []string{
		`CREATE TABLE IF NOT EXISTS nodes (
			id TEXT PRIMARY KEY,
			name TEXT NOT NULL,
			address TEXT NOT NULL,
			grpc_port INTEGER NOT NULL,
			token TEXT NOT NULL DEFAULT '',
			labels_json TEXT NOT NULL DEFAULT '[]',
			status TEXT NOT NULL DEFAULT '',
			last_seen_unix INTEGER NOT NULL DEFAULT 0,
			config_hash TEXT NOT NULL DEFAULT '',
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS node_frps_configs (
			node_id TEXT PRIMARY KEY,
			enabled INTEGER NOT NULL DEFAULT 0,
			bind_addr TEXT NOT NULL DEFAULT '0.0.0.0',
			bind_port INTEGER NOT NULL DEFAULT 7000,
			proxy_bind_addr TEXT NOT NULL DEFAULT '0.0.0.0',
			allow_ports_json TEXT NOT NULL DEFAULT '[]',
			auth_token_ciphertext TEXT NOT NULL DEFAULT '',
			tls_force INTEGER NOT NULL DEFAULT 1,
			max_ports_per_client INTEGER NOT NULL DEFAULT 0,
			desired_hash TEXT NOT NULL DEFAULT '',
			applied_hash TEXT NOT NULL DEFAULT '',
			runtime_state TEXT NOT NULL DEFAULT '',
			frps_version TEXT NOT NULL DEFAULT '',
			last_error TEXT NOT NULL DEFAULT '',
			started_at_unix INTEGER NOT NULL DEFAULT 0,
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL,
			managed_domain_id TEXT,
			FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE,
			FOREIGN KEY (managed_domain_id) REFERENCES managed_domains(id) ON DELETE SET NULL
		)`,
		`CREATE TABLE IF NOT EXISTS inbounds (
			id TEXT PRIMARY KEY,
			name TEXT NOT NULL,
			protocol TEXT NOT NULL,
			params_json TEXT NOT NULL DEFAULT '{}',
			enabled INTEGER NOT NULL DEFAULT 1,
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS node_inbounds (
			node_id TEXT NOT NULL,
			inbound_id TEXT NOT NULL,
			PRIMARY KEY (node_id, inbound_id),
			FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE,
			FOREIGN KEY (inbound_id) REFERENCES inbounds(id) ON DELETE CASCADE
		)`,
		`CREATE TABLE IF NOT EXISTS proxy_chains (
			id TEXT PRIMARY KEY,
			name TEXT NOT NULL COLLATE NOCASE UNIQUE,
			enabled INTEGER NOT NULL DEFAULT 0,
			state TEXT NOT NULL DEFAULT 'disabled',
			last_deploy_unix INTEGER NOT NULL DEFAULT 0,
			last_deploy_error TEXT NOT NULL DEFAULT '',
			last_probe_unix INTEGER NOT NULL DEFAULT 0,
			last_probe_delay_ms INTEGER NOT NULL DEFAULT 0,
			last_probe_error TEXT NOT NULL DEFAULT '',
			failed_hop_index INTEGER NOT NULL DEFAULT -1,
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS proxy_chain_hops (
			chain_id TEXT NOT NULL,
			position INTEGER NOT NULL,
			node_id TEXT NOT NULL,
			inbound_id TEXT NOT NULL,
			dial_address TEXT NOT NULL DEFAULT '',
			dial_port INTEGER NOT NULL DEFAULT 0,
			tls_skip_verify INTEGER NOT NULL DEFAULT 0,
			PRIMARY KEY (chain_id, position),
			UNIQUE (chain_id, node_id),
			UNIQUE (node_id, inbound_id),
			FOREIGN KEY (chain_id) REFERENCES proxy_chains(id) ON DELETE CASCADE,
			FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE RESTRICT,
			FOREIGN KEY (inbound_id) REFERENCES inbounds(id) ON DELETE RESTRICT
		)`,
		`CREATE TABLE IF NOT EXISTS tasks (
			id TEXT PRIMARY KEY,
			type TEXT NOT NULL,
			status TEXT NOT NULL,
			node_ids_json TEXT NOT NULL DEFAULT '[]',
			results_json TEXT NOT NULL DEFAULT '[]',
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL
		)`,
		// agent_commands is the uplink command queue: Panel enqueues immediate
		// operations that uplink nodes (which do not expose a live gRPC control
		// port) pull via long-poll and acknowledge with a result. Semantics are
		// at-least-once + idempotent, guarded by a lease visibility timeout and
		// a TTL for abandoned commands.
		`CREATE TABLE IF NOT EXISTS agent_commands (
			id TEXT PRIMARY KEY,
			node_id TEXT NOT NULL,
			type TEXT NOT NULL,
			payload_json TEXT NOT NULL DEFAULT '{}',
			status TEXT NOT NULL DEFAULT 'pending',
			attempt INTEGER NOT NULL DEFAULT 0,
			lease_expires_unix INTEGER NOT NULL DEFAULT 0,
			result_json TEXT NOT NULL DEFAULT '',
			error TEXT NOT NULL DEFAULT '',
			created_at_unix INTEGER NOT NULL,
			completed_at_unix INTEGER NOT NULL DEFAULT 0,
			expires_at_unix INTEGER NOT NULL DEFAULT 0,
			FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
		)`,
		`CREATE INDEX IF NOT EXISTS idx_agent_commands_node_status
			ON agent_commands (node_id, status, created_at_unix)`,
		`CREATE TABLE IF NOT EXISTS settings (
			id INTEGER PRIMARY KEY CHECK (id = 1),
			admin_password_hash TEXT NOT NULL DEFAULT '',
			default_agent_token TEXT NOT NULL DEFAULT '',
			grpc_timeout_sec INTEGER NOT NULL DEFAULT 10,
			max_concurrency INTEGER NOT NULL DEFAULT 10,
			listen_addr TEXT NOT NULL DEFAULT ':8080',
			public_base_url TEXT NOT NULL DEFAULT ''
		)`,
		`CREATE TABLE IF NOT EXISTS subscriptions (
				id TEXT PRIMARY KEY,
				name TEXT NOT NULL,
				format TEXT NOT NULL,
				token TEXT NOT NULL UNIQUE,
				inbound_ids_json TEXT NOT NULL DEFAULT '[]',
				include_all_inbounds INTEGER NOT NULL DEFAULT 1,
				enabled INTEGER NOT NULL DEFAULT 1,
				created_at_unix INTEGER NOT NULL,
				updated_at_unix INTEGER NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS config_snapshots (
			id TEXT PRIMARY KEY,
			node_id TEXT NOT NULL,
			config_json TEXT NOT NULL,
			config_hash TEXT NOT NULL,
			task_id TEXT NOT NULL DEFAULT '',
			created_at_unix INTEGER NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_config_snapshots_node_created
			ON config_snapshots(node_id, created_at_unix DESC)`,
		`CREATE TABLE IF NOT EXISTS external_sources (
			id TEXT PRIMARY KEY,
			name TEXT NOT NULL,
			url TEXT NOT NULL,
			headers_json TEXT NOT NULL DEFAULT '{}',
			enabled INTEGER NOT NULL DEFAULT 1,
			refresh_interval_sec INTEGER NOT NULL DEFAULT 0,
			last_fetch_unix INTEGER NOT NULL DEFAULT 0,
			last_success_unix INTEGER NOT NULL DEFAULT 0,
			last_error TEXT NOT NULL DEFAULT '',
			content_type TEXT NOT NULL DEFAULT '',
			cached_body TEXT NOT NULL DEFAULT '',
			cached_proxy_count INTEGER NOT NULL DEFAULT 0,
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS subscription_external_sources (
			subscription_id TEXT NOT NULL,
			external_source_id TEXT NOT NULL,
			sort_order INTEGER NOT NULL DEFAULT 0,
			PRIMARY KEY (subscription_id, external_source_id),
			FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE,
			FOREIGN KEY (external_source_id) REFERENCES external_sources(id) ON DELETE CASCADE
		)`,
		`CREATE INDEX IF NOT EXISTS idx_sub_ext_src_sub
			ON subscription_external_sources(subscription_id, sort_order)`,
		`CREATE TABLE IF NOT EXISTS pki_certificates (
			serial TEXT PRIMARY KEY,
			node_id TEXT NOT NULL DEFAULT '',
			profile TEXT NOT NULL,
			subject TEXT NOT NULL DEFAULT '',
			uri_san TEXT NOT NULL DEFAULT '',
			dns_sans TEXT NOT NULL DEFAULT '',
			ip_sans TEXT NOT NULL DEFAULT '',
			not_before_unix INTEGER NOT NULL,
			not_after_unix INTEGER NOT NULL,
			status TEXT NOT NULL DEFAULT 'active',
			revoked_at_unix INTEGER NOT NULL DEFAULT 0,
			revoke_reason TEXT NOT NULL DEFAULT '',
			cert_pem TEXT NOT NULL DEFAULT '',
			created_at_unix INTEGER NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_pki_certificates_node
			ON pki_certificates(node_id, created_at_unix DESC)`,
		`CREATE TABLE IF NOT EXISTS pki_audit_logs (
			id TEXT PRIMARY KEY,
			action TEXT NOT NULL,
			node_id TEXT NOT NULL DEFAULT '',
			serial TEXT NOT NULL DEFAULT '',
			actor TEXT NOT NULL DEFAULT '',
			detail TEXT NOT NULL DEFAULT '',
			created_at_unix INTEGER NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_pki_audit_created
			ON pki_audit_logs(created_at_unix DESC)`,
		`CREATE TABLE IF NOT EXISTS pki_enrollment_tokens (
			token_hash TEXT PRIMARY KEY,
			node_id TEXT NOT NULL,
			expires_at_unix INTEGER NOT NULL,
			used_at_unix INTEGER NOT NULL DEFAULT 0,
			created_at_unix INTEGER NOT NULL,
			FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
		)`,
		`CREATE INDEX IF NOT EXISTS idx_pki_enrollment_node
			ON pki_enrollment_tokens(node_id, created_at_unix DESC)`,
		`CREATE TABLE IF NOT EXISTS dns_accounts (
			id TEXT PRIMARY KEY,
			name TEXT NOT NULL COLLATE NOCASE UNIQUE,
			provider TEXT NOT NULL,
			zone TEXT NOT NULL DEFAULT '',
			credentials_ciphertext TEXT NOT NULL DEFAULT '',
			settings_json TEXT NOT NULL DEFAULT '{}',
			enabled INTEGER NOT NULL DEFAULT 1,
			last_test_unix INTEGER NOT NULL DEFAULT 0,
			last_test_error TEXT NOT NULL DEFAULT '',
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS managed_domains (
			id TEXT PRIMARY KEY,
			node_id TEXT NOT NULL,
			dns_account_id TEXT NOT NULL,
			zone TEXT NOT NULL,
			fqdn TEXT NOT NULL COLLATE NOCASE,
			record_mode TEXT NOT NULL DEFAULT 'a',
			address_source TEXT NOT NULL DEFAULT 'manual',
			manual_ipv4 TEXT NOT NULL DEFAULT '',
			manual_ipv6 TEXT NOT NULL DEFAULT '',
			manual_cname TEXT NOT NULL DEFAULT '',
			ttl INTEGER NOT NULL DEFAULT 300,
			enabled INTEGER NOT NULL DEFAULT 1,
			state TEXT NOT NULL DEFAULT 'pending',
			desired_ipv4 TEXT NOT NULL DEFAULT '',
			desired_ipv6 TEXT NOT NULL DEFAULT '',
			desired_cname TEXT NOT NULL DEFAULT '',
			observed_ipv4_json TEXT NOT NULL DEFAULT '[]',
			observed_ipv6_json TEXT NOT NULL DEFAULT '[]',
			observed_cname_json TEXT NOT NULL DEFAULT '[]',
			provider_record_a_id TEXT NOT NULL DEFAULT '',
			provider_record_aaaa_id TEXT NOT NULL DEFAULT '',
			provider_record_cname_id TEXT NOT NULL DEFAULT '',
			created_a_by_panel INTEGER NOT NULL DEFAULT 0,
			created_aaaa_by_panel INTEGER NOT NULL DEFAULT 0,
			created_cname_by_panel INTEGER NOT NULL DEFAULT 0,
			last_reconcile_unix INTEGER NOT NULL DEFAULT 0,
			next_reconcile_unix INTEGER NOT NULL DEFAULT 0,
			retry_count INTEGER NOT NULL DEFAULT 0,
			last_error TEXT NOT NULL DEFAULT '',
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL,
			UNIQUE (dns_account_id, fqdn),
			FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE,
			FOREIGN KEY (dns_account_id) REFERENCES dns_accounts(id) ON DELETE RESTRICT
		)`,
		`CREATE INDEX IF NOT EXISTS idx_managed_domains_due
			ON managed_domains(enabled, next_reconcile_unix)`,
		`CREATE INDEX IF NOT EXISTS idx_managed_domains_node
			ON managed_domains(node_id, fqdn)`,
		`CREATE TABLE IF NOT EXISTS acme_accounts (
			id TEXT PRIMARY KEY,
			name TEXT NOT NULL COLLATE NOCASE UNIQUE,
			directory_url TEXT NOT NULL,
			email TEXT NOT NULL DEFAULT '',
			account_key_ciphertext TEXT NOT NULL DEFAULT '',
			registration_uri TEXT NOT NULL DEFAULT '',
			eab_key_id TEXT NOT NULL DEFAULT '',
			eab_hmac_ciphertext TEXT NOT NULL DEFAULT '',
			terms_accepted_unix INTEGER NOT NULL DEFAULT 0,
			status TEXT NOT NULL DEFAULT 'pending',
			last_error TEXT NOT NULL DEFAULT '',
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS protocol_certificates (
			id TEXT PRIMARY KEY,
			node_id TEXT NOT NULL,
			managed_domain_id TEXT NOT NULL,
			acme_account_id TEXT NOT NULL,
			domains_json TEXT NOT NULL DEFAULT '[]',
			status TEXT NOT NULL DEFAULT 'pending',
			agent_key_id TEXT NOT NULL DEFAULT '',
			public_key_fingerprint TEXT NOT NULL DEFAULT '',
			candidate_cert_path TEXT NOT NULL DEFAULT '',
			candidate_key_path TEXT NOT NULL DEFAULT '',
			active_cert_path TEXT NOT NULL DEFAULT '',
			active_key_path TEXT NOT NULL DEFAULT '',
			cert_pem TEXT NOT NULL DEFAULT '',
			serial TEXT NOT NULL DEFAULT '',
			fingerprint TEXT NOT NULL DEFAULT '',
			not_before_unix INTEGER NOT NULL DEFAULT 0,
			not_after_unix INTEGER NOT NULL DEFAULT 0,
			renew_after_unix INTEGER NOT NULL DEFAULT 0,
			revision INTEGER NOT NULL DEFAULT 0,
			retry_count INTEGER NOT NULL DEFAULT 0,
			next_retry_unix INTEGER NOT NULL DEFAULT 0,
			last_error TEXT NOT NULL DEFAULT '',
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL,
			UNIQUE (node_id, managed_domain_id),
			FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE,
			FOREIGN KEY (managed_domain_id) REFERENCES managed_domains(id) ON DELETE CASCADE,
			FOREIGN KEY (acme_account_id) REFERENCES acme_accounts(id) ON DELETE RESTRICT
		)`,
		`CREATE INDEX IF NOT EXISTS idx_protocol_certificates_renewal
			ON protocol_certificates(status, renew_after_unix)`,
		`CREATE TABLE IF NOT EXISTS node_inbound_tls_bindings (
			node_id TEXT NOT NULL,
			inbound_id TEXT NOT NULL,
			mode TEXT NOT NULL DEFAULT 'legacy',
			managed_domain_id TEXT,
			certificate_id TEXT,
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL,
			PRIMARY KEY (node_id, inbound_id),
			FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE,
			FOREIGN KEY (inbound_id) REFERENCES inbounds(id) ON DELETE CASCADE,
			FOREIGN KEY (managed_domain_id) REFERENCES managed_domains(id) ON DELETE SET NULL,
			FOREIGN KEY (certificate_id) REFERENCES protocol_certificates(id) ON DELETE SET NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_node_inbound_tls_domain
			ON node_inbound_tls_bindings(managed_domain_id)`,
		`CREATE TABLE IF NOT EXISTS automation_jobs (
			id TEXT PRIMARY KEY,
			type TEXT NOT NULL,
			target_type TEXT NOT NULL,
			target_id TEXT NOT NULL,
			state TEXT NOT NULL DEFAULT 'pending',
			payload_json TEXT NOT NULL DEFAULT '{}',
			attempt INTEGER NOT NULL DEFAULT 0,
			next_run_unix INTEGER NOT NULL DEFAULT 0,
			lease_owner TEXT NOT NULL DEFAULT '',
			lease_expires_unix INTEGER NOT NULL DEFAULT 0,
			last_error TEXT NOT NULL DEFAULT '',
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_automation_jobs_due
			ON automation_jobs(state, next_run_unix, lease_expires_unix)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_automation_jobs_active_target
			ON automation_jobs(type, target_type, target_id)
			WHERE state IN ('pending', 'running', 'retry_wait')`,
		`CREATE TABLE IF NOT EXISTS automation_audit_logs (
			id TEXT PRIMARY KEY,
			action TEXT NOT NULL,
			target_type TEXT NOT NULL DEFAULT '',
			target_id TEXT NOT NULL DEFAULT '',
			actor TEXT NOT NULL DEFAULT '',
			outcome TEXT NOT NULL DEFAULT '',
			detail TEXT NOT NULL DEFAULT '',
			created_at_unix INTEGER NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_automation_audit_created
			ON automation_audit_logs(created_at_unix DESC)`,
		`CREATE TABLE IF NOT EXISTS route_plans (
			id TEXT PRIMARY KEY,
			name TEXT NOT NULL COLLATE NOCASE UNIQUE,
			scope TEXT NOT NULL DEFAULT 'global' CHECK(scope IN ('global','subscription')),
			subscription_id TEXT REFERENCES subscriptions(id) ON DELETE CASCADE,
			enabled INTEGER NOT NULL DEFAULT 1,
			sort_order INTEGER NOT NULL DEFAULT 0,
			created_at_unix INTEGER NOT NULL,
			updated_at_unix INTEGER NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS route_plan_rules (
			plan_id TEXT NOT NULL,
			position INTEGER NOT NULL,
			match_type TEXT NOT NULL CHECK(match_type IN ('domain','domain_suffix','domain_keyword','ip_cidr','process_name')),
			match_value TEXT NOT NULL,
			action TEXT NOT NULL CHECK(action IN ('proxy','direct','block')),
			target_chain_id TEXT REFERENCES proxy_chains(id) ON DELETE RESTRICT,
			enabled INTEGER NOT NULL DEFAULT 1,
			PRIMARY KEY (plan_id, position),
			FOREIGN KEY (plan_id) REFERENCES route_plans(id) ON DELETE CASCADE
		)`,
		`CREATE INDEX IF NOT EXISTS idx_route_plan_rules_chain
			ON route_plan_rules(target_chain_id)`,
	}
	for _, stmt := range stmts {
		if _, err := s.db.Exec(stmt); err != nil {
			return fmt.Errorf("数据库迁移失败：%w", err)
		}
	}
	frpColumnsPresent := false
	frpColumns, err := s.db.Query(`PRAGMA table_info(node_inbounds)`)
	if err != nil {
		return fmt.Errorf("检查节点入站表失败：%w", err)
	}
	for frpColumns.Next() {
		var cid, notNull, primaryKey int
		var name, dataType string
		var defaultValue any
		if err := frpColumns.Scan(&cid, &name, &dataType, &notNull, &defaultValue, &primaryKey); err != nil {
			_ = frpColumns.Close()
			return err
		}
		if name == "frp_enabled" {
			frpColumnsPresent = true
		}
	}
	if err := frpColumns.Err(); err != nil {
		_ = frpColumns.Close()
		return err
	}
	if err := frpColumns.Close(); err != nil {
		return err
	}
	// Additive columns for fleet monitoring (safe to re-run).
	alters := []string{
		`ALTER TABLE nodes ADD COLUMN runtime_state TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE nodes ADD COLUMN agent_version TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE nodes ADD COLUMN singbox_version TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE nodes ADD COLUMN connections INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE nodes ADD COLUMN uplink_bytes INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE nodes ADD COLUMN downlink_bytes INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE nodes ADD COLUMN cpu_percent REAL NOT NULL DEFAULT 0`,
		`ALTER TABLE nodes ADD COLUMN memory_rss_bytes INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE nodes ADD COLUMN metrics_at_unix INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE nodes ADD COLUMN last_error TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE nodes ADD COLUMN egress_interface TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE nodes ADD COLUMN public_address TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE nodes ADD COLUMN port_mappings_json TEXT NOT NULL DEFAULT '[]'`,
		`ALTER TABLE nodes ADD COLUMN capabilities_json TEXT NOT NULL DEFAULT '[]'`,
		`ALTER TABLE nodes ADD COLUMN pki_ca_bundle_pem TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE nodes ADD COLUMN pki_cert_serial TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE nodes ADD COLUMN pki_not_after_unix INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE nodes ADD COLUMN ddns_enabled INTEGER NOT NULL DEFAULT 1`,
		`ALTER TABLE nodes ADD COLUMN control_mode TEXT NOT NULL DEFAULT 'push'`,
		`ALTER TABLE nodes ADD COLUMN desired_runtime TEXT NOT NULL DEFAULT 'running'`,
		`ALTER TABLE nodes ADD COLUMN uplink_last_seen_unix INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE nodes ADD COLUMN agent_enrolled INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE node_frps_configs ADD COLUMN managed_domain_id TEXT REFERENCES managed_domains(id) ON DELETE SET NULL`,
		`ALTER TABLE node_inbounds ADD COLUMN public_address TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE node_inbounds ADD COLUMN public_port INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE node_inbounds ADD COLUMN frp_enabled INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE node_inbounds ADD COLUMN frpc_config TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE settings ADD COLUMN public_base_url TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE settings ADD COLUMN chain_probe_url TEXT NOT NULL DEFAULT 'https://www.gstatic.com/generate_204'`,
		`ALTER TABLE settings ADD COLUMN chain_probe_interval_sec INTEGER NOT NULL DEFAULT 60`,
		`ALTER TABLE settings ADD COLUMN chain_probe_timeout_sec INTEGER NOT NULL DEFAULT 10`,
		`ALTER TABLE settings ADD COLUMN chain_subscription_migrated INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE settings ADD COLUMN session_version INTEGER NOT NULL DEFAULT 1`,
		`ALTER TABLE settings ADD COLUMN trusted_proxy_cidrs TEXT NOT NULL DEFAULT ''`,
		// Nullable during migration so legacy rows can be backfilled from inbound_ids_json.
		`ALTER TABLE subscriptions ADD COLUMN include_all_inbounds INTEGER`,
		`ALTER TABLE subscriptions ADD COLUMN include_standalone INTEGER NOT NULL DEFAULT 1`,
		`ALTER TABLE subscriptions ADD COLUMN chain_ids_json TEXT NOT NULL DEFAULT '[]'`,
		`ALTER TABLE subscriptions ADD COLUMN include_all_chains INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE subscriptions ADD COLUMN route_plan_id TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE subscriptions ADD COLUMN disabled INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE dns_accounts ADD COLUMN zone TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE managed_domains ADD COLUMN manual_cname TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE managed_domains ADD COLUMN desired_cname TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE managed_domains ADD COLUMN observed_cname_json TEXT NOT NULL DEFAULT '[]'`,
		`ALTER TABLE managed_domains ADD COLUMN provider_record_cname_id TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE managed_domains ADD COLUMN created_cname_by_panel INTEGER NOT NULL DEFAULT 0`,
	}
	for _, stmt := range alters {
		_, _ = s.db.Exec(stmt) // ignore "duplicate column" on existing DBs
	}
	// v0.15.3 stored FRP on the reusable inbound template. Migrate once;
	// retain unattached and chain-hop templates to avoid discarding settings.
	if !frpColumnsPresent {
		if _, err := s.db.Exec(`
		UPDATE node_inbounds SET frp_enabled = 1,
			frpc_config = COALESCE((SELECT json_extract(params_json, '$.frpc_config') FROM inbounds WHERE id = node_inbounds.inbound_id), '')
		WHERE frp_enabled = 0 AND inbound_id IN (
			SELECT id FROM inbounds WHERE json_valid(params_json) AND json_extract(params_json, '$.frp_enabled') = 1
		)`); err != nil {
			return fmt.Errorf("迁移节点 FRP 关联失败：%w", err)
		}
		if _, err := s.db.Exec(`
		UPDATE inbounds SET params_json = json_remove(params_json, '$.frp_enabled', '$.frpc_config')
		WHERE json_valid(params_json) AND id IN (SELECT inbound_id FROM node_inbounds)
			AND id NOT IN (SELECT inbound_id FROM proxy_chain_hops)
			AND (json_type(params_json, '$.frp_enabled') IS NOT NULL OR json_type(params_json, '$.frpc_config') IS NOT NULL)`); err != nil {
			return fmt.Errorf("清理旧入站 FRP 参数失败：%w", err)
		}
	}
	// v0.10.0 stored the provider zone in each managed domain and exposed a
	// temporary test_zone setting. Preserve accounts that already manage one
	// unambiguous zone; accounts spanning multiple zones must be split by the
	// operator under the one-account-one-zone model.
	if _, err := s.db.Exec(`
		UPDATE dns_accounts
		SET zone = (
			SELECT MIN(zone)
			FROM managed_domains
			WHERE managed_domains.dns_account_id = dns_accounts.id
		)
		WHERE zone = ''
			AND 1 = (
				SELECT COUNT(DISTINCT zone)
				FROM managed_domains
				WHERE managed_domains.dns_account_id = dns_accounts.id
			)`); err != nil {
		return fmt.Errorf("迁移 DNS 账号区域失败：%w", err)
	}
	// HTTP Callback was removed after v0.10.0. Disable any legacy Callback
	// automation without deleting external DNS records or encrypted account
	// data, so operators can migrate deliberately to a supported provider.
	if _, err := s.db.Exec(`
		UPDATE dns_accounts
		SET enabled = 0,
			last_test_error = 'HTTP Callback DNS 供应商已停止支持，请迁移到 AliDNS、DNSPod 或 Cloudflare'
		WHERE provider = 'callback'`); err != nil {
		return fmt.Errorf("停用旧 HTTP Callback DNS 账号失败：%w", err)
	}
	if _, err := s.db.Exec(`
		UPDATE managed_domains
		SET enabled = 0,
			state = 'disabled',
			last_error = '关联的 HTTP Callback DNS 供应商已停止支持'
		WHERE dns_account_id IN (
			SELECT id FROM dns_accounts WHERE provider = 'callback'
		)`); err != nil {
		return fmt.Errorf("停用旧 HTTP Callback 托管域名失败：%w", err)
	}
	if _, err := s.db.Exec(`
		UPDATE dns_accounts
		SET zone = LOWER(TRIM(json_extract(settings_json, '$.test_zone'), '.'))
		WHERE zone = ''
			AND json_valid(settings_json)
			AND COALESCE(json_extract(settings_json, '$.test_zone'), '') <> ''
			AND 0 = (
				SELECT COUNT(DISTINCT zone)
				FROM managed_domains
				WHERE managed_domains.dns_account_id = dns_accounts.id
			)`); err != nil {
		return fmt.Errorf("迁移 DNS 账号验证区域失败：%w", err)
	}
	// These columns belonged to removed management-TLS and one-time upgrade
	// implementations and are deliberately not retained.
	for _, column := range []string{"tls_skip_verify", "ca_cert_pem", "pki_migration_required"} {
		if _, err := s.db.Exec(`ALTER TABLE nodes DROP COLUMN ` + column); err != nil &&
			!strings.Contains(strings.ToLower(err.Error()), "no such column") {
			return fmt.Errorf("删除旧节点字段 %s 失败：%w", column, err)
		}
	}
	if _, err := s.db.Exec(`
		UPDATE subscriptions
		SET include_all_inbounds = CASE
			WHEN TRIM(inbound_ids_json) IN ('', '[]', 'null') THEN 1
			ELSE 0
		END
		WHERE include_all_inbounds IS NULL`); err != nil {
		return fmt.Errorf("迁移订阅本地入站模式失败：%w", err)
	}
	return nil
}

func (s *Store) ensureDefaultSettings() error {
	var n int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM settings WHERE id = 1`).Scan(&n); err != nil {
		return fmt.Errorf("检查系统设置失败：%w", err)
	}
	if n > 0 {
		return nil
	}
	_, err := s.db.Exec(`
		INSERT INTO settings (id, admin_password_hash, default_agent_token, grpc_timeout_sec, max_concurrency, listen_addr)
		VALUES (1, '', '', 10, 10, ':8080')`)
	if err != nil {
		return fmt.Errorf("写入默认系统设置失败：%w", err)
	}
	return nil
}

func nowUnix() int64 {
	return time.Now().Unix()
}

func newID() string {
	return uuid.NewString()
}

func marshalJSON(v any) (string, error) {
	b, err := json.Marshal(v)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func unmarshalJSON[T any](s string, dest *T) error {
	if s == "" {
		return nil
	}
	return json.Unmarshal([]byte(s), dest)
}

func boolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

// --- Nodes ---

func validateControlMode(mode string) error {
	switch mode {
	case ControlModePush, ControlModeUplink:
		return nil
	default:
		return fmt.Errorf("control_mode 只能是 push 或 uplink")
	}
}

func normalizeControlMode(mode string) (string, error) {
	mode = strings.TrimSpace(mode)
	if mode == "" {
		return ControlModePush, nil
	}
	if err := validateControlMode(mode); err != nil {
		return "", err
	}
	return mode, nil
}

func validateDesiredRuntime(state string) error {
	switch state {
	case DesiredRuntimeRunning, DesiredRuntimeStopped:
		return nil
	default:
		return fmt.Errorf("desired_runtime 只能是 running 或 stopped")
	}
}

func normalizeDesiredRuntime(state string) (string, error) {
	state = strings.TrimSpace(state)
	if state == "" {
		return DesiredRuntimeRunning, nil
	}
	if err := validateDesiredRuntime(state); err != nil {
		return "", err
	}
	return state, nil
}

func (s *Store) CreateNode(n *Node) error {
	if n == nil {
		return fmt.Errorf("节点不能为空")
	}
	if n.ID == "" {
		n.ID = newID()
	}
	now := nowUnix()
	if n.CreatedAtUnix == 0 {
		n.CreatedAtUnix = now
	}
	if n.UpdatedAtUnix == 0 {
		n.UpdatedAtUnix = now
	}
	if n.Labels == nil {
		n.Labels = []string{}
	}
	mode, err := normalizeControlMode(n.ControlMode)
	if err != nil {
		return err
	}
	n.ControlMode = mode
	desired, err := normalizeDesiredRuntime(n.DesiredRuntime)
	if err != nil {
		return err
	}
	n.DesiredRuntime = desired
	n.PortMappings = NormalizePortMappings(n.PortMappings)
	labelsJSON, err := marshalJSON(n.Labels)
	if err != nil {
		return fmt.Errorf("编码标签失败：%w", err)
	}
	mappingsJSON, err := marshalJSON(n.PortMappings)
	if err != nil {
		return fmt.Errorf("编码端口映射失败：%w", err)
	}
	capabilitiesJSON, err := marshalJSON(n.Capabilities)
	if err != nil {
		return fmt.Errorf("编码节点能力失败：%w", err)
	}
	_, err = s.db.Exec(`
		INSERT INTO nodes (
			id, name, address, grpc_port, token, labels_json,
			pki_ca_bundle_pem, pki_cert_serial, pki_not_after_unix,
			status, last_seen_unix, config_hash,
			runtime_state, agent_version, singbox_version,
			connections, uplink_bytes, downlink_bytes, cpu_percent, memory_rss_bytes,
			metrics_at_unix, last_error, egress_interface, public_address, port_mappings_json, capabilities_json,
			ddns_enabled, control_mode, desired_runtime, uplink_last_seen_unix, created_at_unix, updated_at_unix
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		n.ID, n.Name, n.Address, n.GRPCPort, n.Token, labelsJSON, n.PKICABundlePEM,
		n.PKICertSerial, n.PKINotAfter,
		n.Status, n.LastSeenUnix, n.ConfigHash,
		n.RuntimeState, n.AgentVersion, n.SingboxVersion,
		n.Connections, n.UplinkBytes, n.DownlinkBytes, n.CPUPercent, n.MemoryRSSBytes,
		n.MetricsAtUnix, n.LastError, n.EgressInterface, n.PublicAddress, mappingsJSON, capabilitiesJSON,
		boolToInt(n.DDNSEnabled), n.ControlMode, n.DesiredRuntime, n.UplinkLastSeenUnix, n.CreatedAtUnix, n.UpdatedAtUnix,
	)
	if err != nil {
		return fmt.Errorf("创建节点失败：%w", err)
	}
	return nil
}

func (s *Store) UpdateNode(n *Node) error {
	if n == nil || n.ID == "" {
		return fmt.Errorf("必须提供节点 ID")
	}
	n.UpdatedAtUnix = nowUnix()
	if n.Labels == nil {
		n.Labels = []string{}
	}
	mode, err := normalizeControlMode(n.ControlMode)
	if err != nil {
		return err
	}
	n.ControlMode = mode
	desired, err := normalizeDesiredRuntime(n.DesiredRuntime)
	if err != nil {
		return err
	}
	n.DesiredRuntime = desired
	n.PortMappings = NormalizePortMappings(n.PortMappings)
	labelsJSON, err := marshalJSON(n.Labels)
	if err != nil {
		return fmt.Errorf("编码标签失败：%w", err)
	}
	mappingsJSON, err := marshalJSON(n.PortMappings)
	if err != nil {
		return fmt.Errorf("编码端口映射失败：%w", err)
	}
	capabilitiesJSON, err := marshalJSON(n.Capabilities)
	if err != nil {
		return fmt.Errorf("编码节点能力失败：%w", err)
	}
	res, err := s.db.Exec(`
		UPDATE nodes SET
			name = ?, address = ?, grpc_port = ?, token = ?, labels_json = ?,
			pki_ca_bundle_pem = ?,
			status = ?, last_seen_unix = ?,
			pki_cert_serial = ?, pki_not_after_unix = ?,
			config_hash = ?,
			runtime_state = ?, agent_version = ?, singbox_version = ?,
			connections = ?, uplink_bytes = ?, downlink_bytes = ?, cpu_percent = ?, memory_rss_bytes = ?,
			metrics_at_unix = ?, last_error = ?, egress_interface = ?, public_address = ?,
			port_mappings_json = ?, capabilities_json = ?, ddns_enabled = ?,
			control_mode = ?, desired_runtime = ?, uplink_last_seen_unix = ?,
			updated_at_unix = ?
		WHERE id = ?`,
		n.Name, n.Address, n.GRPCPort, n.Token, labelsJSON,
		n.PKICABundlePEM, n.Status, n.LastSeenUnix,
		n.PKICertSerial, n.PKINotAfter,
		n.ConfigHash,
		n.RuntimeState, n.AgentVersion, n.SingboxVersion,
		n.Connections, n.UplinkBytes, n.DownlinkBytes, n.CPUPercent, n.MemoryRSSBytes,
		n.MetricsAtUnix, n.LastError, n.EgressInterface, n.PublicAddress,
		mappingsJSON, capabilitiesJSON, boolToInt(n.DDNSEnabled),
		n.ControlMode, n.DesiredRuntime, n.UplinkLastSeenUnix,
		n.UpdatedAtUnix, n.ID,
	)
	if err != nil {
		return fmt.Errorf("更新节点失败：%w", err)
	}
	affected, _ := res.RowsAffected()
	if affected == 0 {
		return fmt.Errorf("节点不存在：%s", n.ID)
	}
	return nil
}

// UpdateNodeOperatorFields updates only operator-owned columns. An address edit
// adjusts status atomically; metrics, versions and config hashes stay untouched.
func (s *Store) UpdateNodeOperatorFields(id string, update NodeOperatorUpdate) error {
	if id == "" {
		return fmt.Errorf("必须提供节点 ID")
	}

	sets := make([]string, 0, 12)
	args := make([]any, 0, 14)
	add := func(column string, value any) {
		sets = append(sets, column+" = ?")
		args = append(args, value)
	}

	if update.Name != nil {
		add("name", *update.Name)
	}
	if update.Address != nil {
		add("address", *update.Address)
		sets = append(sets, `status = CASE
			WHEN ? = '' THEN 'pending'
			WHEN status = 'pending' THEN 'unknown'
			ELSE status
		END`)
		args = append(args, *update.Address)
	}
	if update.GRPCPort != nil {
		add("grpc_port", *update.GRPCPort)
	}
	if update.Token != nil {
		add("token", *update.Token)
	}
	if update.Labels != nil {
		labels := append([]string{}, (*update.Labels)...)
		labelsJSON, err := marshalJSON(labels)
		if err != nil {
			return fmt.Errorf("编码标签失败：%w", err)
		}
		add("labels_json", labelsJSON)
	}
	if update.PublicAddress != nil {
		add("public_address", *update.PublicAddress)
	}
	if update.PortMappings != nil {
		mappingsJSON, err := marshalJSON(NormalizePortMappings(*update.PortMappings))
		if err != nil {
			return fmt.Errorf("编码端口映射失败：%w", err)
		}
		add("port_mappings_json", mappingsJSON)
	}
	if update.EgressInterface != nil {
		add("egress_interface", *update.EgressInterface)
	}
	if update.DDNSEnabled != nil {
		add("ddns_enabled", boolToInt(*update.DDNSEnabled))
	}
	if update.ControlMode != nil {
		mode := strings.TrimSpace(*update.ControlMode)
		if err := validateControlMode(mode); err != nil {
			return err
		}
		add("control_mode", mode)
	}
	if update.DesiredRuntime != nil {
		state := strings.TrimSpace(*update.DesiredRuntime)
		if err := validateDesiredRuntime(state); err != nil {
			return err
		}
		add("desired_runtime", state)
	}

	add("updated_at_unix", nowUnix())
	args = append(args, id)
	res, err := s.db.Exec(`UPDATE nodes SET `+strings.Join(sets, ", ")+` WHERE id = ?`, args...)
	if err != nil {
		return fmt.Errorf("更新节点管理字段失败：%w", err)
	}
	rows, _ := res.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("节点不存在：%s", id)
	}
	return nil
}

// ApplyNodeReport updates only report/live columns. Older collected_at_unix samples are dropped.
func (s *Store) ApplyNodeReport(nodeID string, report NodeReport) (bool, error) {
	if nodeID == "" {
		return false, fmt.Errorf("必须提供节点 ID")
	}
	if report.CPUPercent < 0 || report.CPUPercent > 100 {
		return false, fmt.Errorf("CPU 使用率无效")
	}
	if report.Connections < 0 || report.UplinkBytes < 0 || report.DownlinkBytes < 0 || report.MemoryRSSBytes < 0 {
		return false, fmt.Errorf("上报指标不能为负数")
	}
	collected := report.CollectedAtUnix
	if collected < 0 {
		return false, fmt.Errorf("上报时间戳无效")
	}
	now := nowUnix()
	if collected == 0 {
		collected = now
	}
	if collected > now+300 {
		return false, fmt.Errorf("上报时间戳超出允许范围")
	}

	capsJSON := "[]"
	updateCaps := 0
	if report.HasCapabilities {
		updateCaps = 1
		if report.Capabilities == nil {
			report.Capabilities = []string{}
		}
		encoded, err := marshalJSON(report.Capabilities)
		if err != nil {
			return false, fmt.Errorf("编码节点能力失败：%w", err)
		}
		capsJSON = encoded
	}
	updateMetrics := 0
	if report.HasMetrics {
		updateMetrics = 1
	}
	updateHash := 0
	if report.ConfigHash != "" {
		updateHash = 1
	}
	updateAgent := 0
	if report.AgentVersion != "" {
		updateAgent = 1
	}
	updateSingbox := 0
	if report.SingboxVersion != "" {
		updateSingbox = 1
	}

	res, err := s.db.Exec(`
		UPDATE nodes SET
			status = CASE WHEN ? != '' THEN ? ELSE status END,
			last_seen_unix = ?,
			runtime_state = CASE WHEN ? != '' THEN ? ELSE runtime_state END,
			config_hash = CASE WHEN ? != 0 THEN ? ELSE config_hash END,
			last_error = ?,
			connections = CASE WHEN ? != 0 THEN ? ELSE connections END,
			uplink_bytes = CASE WHEN ? != 0 THEN ? ELSE uplink_bytes END,
			downlink_bytes = CASE WHEN ? != 0 THEN ? ELSE downlink_bytes END,
			cpu_percent = CASE WHEN ? != 0 THEN ? ELSE cpu_percent END,
			memory_rss_bytes = CASE WHEN ? != 0 THEN ? ELSE memory_rss_bytes END,
			metrics_at_unix = CASE WHEN ? != 0 THEN ? ELSE metrics_at_unix END,
			capabilities_json = CASE WHEN ? != 0 THEN ? ELSE capabilities_json END,
			agent_version = CASE WHEN ? != 0 THEN ? ELSE agent_version END,
			singbox_version = CASE WHEN ? != 0 THEN ? ELSE singbox_version END,
			uplink_last_seen_unix = ?,
			updated_at_unix = ?
		WHERE id = ? AND uplink_last_seen_unix <= ?`,
		report.Status, report.Status,
		collected,
		report.RuntimeState, report.RuntimeState,
		updateHash, report.ConfigHash,
		report.LastError,
		updateMetrics, report.Connections,
		updateMetrics, report.UplinkBytes,
		updateMetrics, report.DownlinkBytes,
		updateMetrics, report.CPUPercent,
		updateMetrics, report.MemoryRSSBytes,
		updateMetrics, collected,
		updateCaps, capsJSON,
		updateAgent, report.AgentVersion,
		updateSingbox, report.SingboxVersion,
		collected, now,
		nodeID, collected,
	)
	if err != nil {
		return false, fmt.Errorf("写入节点上报失败：%w", err)
	}
	rows, _ := res.RowsAffected()
	if rows == 0 {
		var exists int
		if err := s.db.QueryRow(`SELECT COUNT(1) FROM nodes WHERE id = ?`, nodeID).Scan(&exists); err != nil {
			return false, fmt.Errorf("检查节点失败：%w", err)
		}
		if exists == 0 {
			return false, fmt.Errorf("节点不存在：%s", nodeID)
		}
		return false, nil
	}
	return true, nil
}

// MarkUplinkUnreachable sets status only when the newest accepted report is still older
// than cutoffUnix, so a concurrent ApplyNodeReport cannot be overwritten.
func (s *Store) MarkUplinkUnreachable(nodeID, lastError string, cutoffUnix int64) error {
	if nodeID == "" {
		return fmt.Errorf("必须提供节点 ID")
	}
	_, err := s.db.Exec(`
		UPDATE nodes SET status = 'unreachable', last_error = ?, updated_at_unix = ?
		WHERE id = ? AND control_mode = ? AND uplink_last_seen_unix > 0 AND uplink_last_seen_unix < ?`,
		lastError, nowUnix(), nodeID, ControlModeUplink, cutoffUnix,
	)
	if err != nil {
		return fmt.Errorf("标记 uplink 节点不可达失败：%w", err)
	}
	return nil
}

func (s *Store) DeleteNode(id string) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()

	rows, err := tx.Query(`
		SELECT DISTINCT c.name
		FROM proxy_chain_hops h
		JOIN proxy_chains c ON c.id = h.chain_id
		WHERE h.node_id = ?
		ORDER BY c.name`, id)
	if err != nil {
		return fmt.Errorf("检查节点的代理链引用失败：%w", err)
	}
	var chainNames []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			_ = rows.Close()
			return fmt.Errorf("读取节点的代理链引用失败：%w", err)
		}
		chainNames = append(chainNames, name)
	}
	if err := rows.Close(); err != nil {
		return fmt.Errorf("关闭代理链引用查询失败：%w", err)
	}
	if len(chainNames) > 0 {
		return fmt.Errorf("节点仍被代理链引用：%s；请先替换对应跳点或删除代理链", strings.Join(chainNames, "、"))
	}

	var runningAutomation int
	if err := tx.QueryRow(`
		SELECT COUNT(*) FROM automation_jobs
		WHERE state = 'running' AND (
			(target_type = 'managed_domain' AND target_id IN (
				SELECT id FROM managed_domains WHERE node_id = ?
			)) OR
			(target_type = 'protocol_certificate' AND target_id IN (
				SELECT id FROM protocol_certificates WHERE node_id = ?
			))
		)`, id, id,
	).Scan(&runningAutomation); err != nil {
		return fmt.Errorf("检查节点自动化任务失败：%w", err)
	}
	if runningAutomation > 0 {
		return fmt.Errorf("节点有 %d 个正在执行的 DNS/证书任务，请等待任务结束后再删除", runningAutomation)
	}
	if _, err := tx.Exec(`
		DELETE FROM automation_jobs
		WHERE target_type = 'protocol_certificate'
			AND target_id IN (SELECT id FROM protocol_certificates WHERE node_id = ?)`,
		id,
	); err != nil {
		return fmt.Errorf("取消节点协议证书任务失败：%w", err)
	}
	if _, err := tx.Exec(`
		DELETE FROM automation_jobs
		WHERE target_type = 'managed_domain'
			AND target_id IN (SELECT id FROM managed_domains WHERE node_id = ?)`,
		id,
	); err != nil {
		return fmt.Errorf("取消节点 DNS 任务失败：%w", err)
	}
	if _, err := tx.Exec(`DELETE FROM node_inbounds WHERE node_id = ?`, id); err != nil {
		return fmt.Errorf("删除节点入站关联失败：%w", err)
	}
	res, err := tx.Exec(`DELETE FROM nodes WHERE id = ?`, id)
	if err != nil {
		return fmt.Errorf("删除节点失败：%w", err)
	}
	affected, _ := res.RowsAffected()
	if affected == 0 {
		return fmt.Errorf("节点不存在：%s", id)
	}
	return tx.Commit()
}

func scanNode(row interface {
	Scan(dest ...any) error
}) (*Node, error) {
	var n Node
	var labelsJSON string
	var mappingsJSON string
	var capabilitiesJSON string
	var ddnsEnabled int
	err := row.Scan(
		&n.ID, &n.Name, &n.Address, &n.GRPCPort, &n.Token, &labelsJSON, &n.PKICABundlePEM,
		&n.PKICertSerial, &n.PKINotAfter,
		&n.Status, &n.LastSeenUnix, &n.ConfigHash,
		&n.RuntimeState, &n.AgentVersion, &n.SingboxVersion,
		&n.Connections, &n.UplinkBytes, &n.DownlinkBytes, &n.CPUPercent, &n.MemoryRSSBytes,
		&n.MetricsAtUnix, &n.LastError, &n.EgressInterface, &n.PublicAddress, &mappingsJSON, &capabilitiesJSON,
		&ddnsEnabled, &n.ControlMode, &n.DesiredRuntime, &n.UplinkLastSeenUnix, &n.CreatedAtUnix, &n.UpdatedAtUnix,
	)
	if err != nil {
		return nil, err
	}
	n.DDNSEnabled = ddnsEnabled != 0
	if n.ControlMode == "" {
		n.ControlMode = ControlModePush
	}
	if n.DesiredRuntime == "" {
		n.DesiredRuntime = DesiredRuntimeRunning
	}
	n.Labels = []string{}
	if err := unmarshalJSON(labelsJSON, &n.Labels); err != nil {
		return nil, fmt.Errorf("解析标签失败：%w", err)
	}
	n.PortMappings = []PortMapping{}
	if err := unmarshalJSON(mappingsJSON, &n.PortMappings); err != nil {
		return nil, fmt.Errorf("解析端口映射失败：%w", err)
	}
	n.PortMappings = NormalizePortMappings(n.PortMappings)
	n.Capabilities = []string{}
	if err := unmarshalJSON(capabilitiesJSON, &n.Capabilities); err != nil {
		return nil, fmt.Errorf("解析节点能力失败：%w", err)
	}
	return &n, nil
}

const nodeSelectCols = `id, name, address, grpc_port, token, labels_json, pki_ca_bundle_pem,
	pki_cert_serial, pki_not_after_unix,
	status, last_seen_unix, config_hash,
	runtime_state, agent_version, singbox_version,
	connections, uplink_bytes, downlink_bytes, cpu_percent, memory_rss_bytes,
	metrics_at_unix, last_error, egress_interface, public_address, port_mappings_json, capabilities_json,
	ddns_enabled, control_mode, desired_runtime, uplink_last_seen_unix, created_at_unix, updated_at_unix`

func (s *Store) GetNode(id string) (*Node, error) {
	row := s.db.QueryRow(`SELECT `+nodeSelectCols+` FROM nodes WHERE id = ?`, id)
	n, err := scanNode(row)
	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("节点不存在：%s", id)
	}
	if err != nil {
		return nil, fmt.Errorf("读取节点失败：%w", err)
	}
	return n, nil
}

// GetNodeByToken returns the unique node with this non-empty control token.
// Empty token is rejected. Multiple matches return an error (ambiguous).
func (s *Store) GetNodeByToken(token string) (*Node, error) {
	token = strings.TrimSpace(token)
	if token == "" {
		return nil, fmt.Errorf("必须提供令牌")
	}
	rows, err := s.db.Query(`SELECT `+nodeSelectCols+` FROM nodes WHERE token = ?`, token)
	if err != nil {
		return nil, fmt.Errorf("按令牌查询节点失败：%w", err)
	}
	defer rows.Close()
	var found *Node
	for rows.Next() {
		n, err := scanNode(rows)
		if err != nil {
			return nil, fmt.Errorf("读取令牌对应节点失败：%w", err)
		}
		if found != nil {
			return nil, fmt.Errorf("多个节点使用了相同令牌")
		}
		found = n
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if found == nil {
		return nil, fmt.Errorf("未找到令牌对应的节点")
	}
	return found, nil
}

func (s *Store) ListNodes() ([]Node, error) {
	rows, err := s.db.Query(`SELECT ` + nodeSelectCols + ` FROM nodes ORDER BY created_at_unix ASC`)
	if err != nil {
		return nil, fmt.Errorf("查询节点列表失败：%w", err)
	}
	defer rows.Close()

	var out []Node
	for rows.Next() {
		n, err := scanNode(rows)
		if err != nil {
			return nil, fmt.Errorf("读取节点列表失败：%w", err)
		}
		out = append(out, *n)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if out == nil {
		out = []Node{}
	}
	return out, nil
}

// ListNodesByLabels returns nodes that have any of the given labels.
func (s *Store) ListNodesByLabels(labels []string) ([]Node, error) {
	if len(labels) == 0 {
		return []Node{}, nil
	}
	nodes, err := s.ListNodes()
	if err != nil {
		return nil, err
	}
	want := make(map[string]struct{}, len(labels))
	for _, l := range labels {
		want[l] = struct{}{}
	}
	var out []Node
	for _, n := range nodes {
		for _, l := range n.Labels {
			if _, ok := want[l]; ok {
				out = append(out, n)
				break
			}
		}
	}
	if out == nil {
		out = []Node{}
	}
	return out, nil
}

// --- Inbounds ---

func (s *Store) CreateInbound(in *InboundConfig) error {
	if in == nil {
		return fmt.Errorf("入站不能为空")
	}
	if in.ID == "" {
		in.ID = newID()
	}
	now := nowUnix()
	if in.CreatedAtUnix == 0 {
		in.CreatedAtUnix = now
	}
	if in.UpdatedAtUnix == 0 {
		in.UpdatedAtUnix = now
	}
	if in.Params == nil {
		in.Params = map[string]any{}
	}
	paramsJSON, err := marshalJSON(in.Params)
	if err != nil {
		return fmt.Errorf("编码入站参数失败：%w", err)
	}
	_, err = s.db.Exec(`
		INSERT INTO inbounds (id, name, protocol, params_json, enabled, created_at_unix, updated_at_unix)
		VALUES (?, ?, ?, ?, ?, ?, ?)`,
		in.ID, in.Name, in.Protocol, paramsJSON, boolToInt(in.Enabled), in.CreatedAtUnix, in.UpdatedAtUnix,
	)
	if err != nil {
		return fmt.Errorf("创建入站失败：%w", err)
	}
	return nil
}

func (s *Store) UpdateInbound(in *InboundConfig) error {
	if in == nil || in.ID == "" {
		return fmt.Errorf("必须提供入站 ID")
	}
	in.UpdatedAtUnix = nowUnix()
	if in.Params == nil {
		in.Params = map[string]any{}
	}
	paramsJSON, err := marshalJSON(in.Params)
	if err != nil {
		return fmt.Errorf("编码入站参数失败：%w", err)
	}
	res, err := s.db.Exec(`
		UPDATE inbounds SET name = ?, protocol = ?, params_json = ?, enabled = ?, updated_at_unix = ?
		WHERE id = ?`,
		in.Name, in.Protocol, paramsJSON, boolToInt(in.Enabled), in.UpdatedAtUnix, in.ID,
	)
	if err != nil {
		return fmt.Errorf("更新入站失败：%w", err)
	}
	rows, _ := res.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("入站不存在：%s", in.ID)
	}
	return nil
}

func (s *Store) DeleteInbound(id string) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()

	if _, err := tx.Exec(`DELETE FROM node_inbounds WHERE inbound_id = ?`, id); err != nil {
		return fmt.Errorf("删除节点入站关联失败：%w", err)
	}
	res, err := tx.Exec(`DELETE FROM inbounds WHERE id = ?`, id)
	if err != nil {
		return fmt.Errorf("删除入站失败：%w", err)
	}
	rows, _ := res.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("入站不存在：%s", id)
	}
	return tx.Commit()
}

func scanInbound(row interface {
	Scan(dest ...any) error
}) (*InboundConfig, error) {
	var in InboundConfig
	var paramsJSON string
	var enabled int
	err := row.Scan(&in.ID, &in.Name, &in.Protocol, &paramsJSON, &enabled, &in.CreatedAtUnix, &in.UpdatedAtUnix)
	if err != nil {
		return nil, err
	}
	in.Enabled = enabled != 0
	in.Params = map[string]any{}
	if err := unmarshalJSON(paramsJSON, &in.Params); err != nil {
		return nil, fmt.Errorf("解析入站参数失败：%w", err)
	}
	return &in, nil
}

const inboundSelectCols = `id, name, protocol, params_json, enabled, created_at_unix, updated_at_unix`

func (s *Store) GetInbound(id string) (*InboundConfig, error) {
	row := s.db.QueryRow(`SELECT `+inboundSelectCols+` FROM inbounds WHERE id = ?`, id)
	in, err := scanInbound(row)
	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("入站不存在：%s", id)
	}
	if err != nil {
		return nil, fmt.Errorf("读取入站失败：%w", err)
	}
	return in, nil
}

func (s *Store) ListInbounds() ([]InboundConfig, error) {
	rows, err := s.db.Query(`SELECT ` + inboundSelectCols + ` FROM inbounds ORDER BY created_at_unix ASC`)
	if err != nil {
		return nil, fmt.Errorf("查询入站列表失败：%w", err)
	}
	defer rows.Close()

	var out []InboundConfig
	for rows.Next() {
		in, err := scanInbound(rows)
		if err != nil {
			return nil, fmt.Errorf("读取入站列表失败：%w", err)
		}
		out = append(out, *in)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if out == nil {
		out = []InboundConfig{}
	}
	return out, nil
}

// --- Attachments ---

// SetNodeInbounds attaches inbound IDs without NAT overrides (compat helper).
func (s *Store) SetNodeInbounds(nodeID string, inboundIDs []string) error {
	bindings := make([]NodeInboundBinding, 0, len(inboundIDs))
	for _, id := range inboundIDs {
		if strings.TrimSpace(id) == "" {
			continue
		}
		bindings = append(bindings, NodeInboundBinding{InboundID: id})
	}
	return s.SetNodeInboundBindings(nodeID, bindings)
}

// SetNodeInboundBindings replaces attachments for a node, including optional per-inbound NAT fields.
func (s *Store) SetNodeInboundBindings(nodeID string, bindings []NodeInboundBinding) error {
	// Ensure node exists.
	if _, err := s.GetNode(nodeID); err != nil {
		return err
	}
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()

	if _, err := tx.Exec(`DELETE FROM node_inbounds WHERE node_id = ?`, nodeID); err != nil {
		return fmt.Errorf("清空节点入站关联失败：%w", err)
	}
	seen := map[string]bool{}
	for _, b := range bindings {
		iid := strings.TrimSpace(b.InboundID)
		if iid == "" || seen[iid] {
			continue
		}
		seen[iid] = true
		var exists int
		if err := tx.QueryRow(`SELECT COUNT(*) FROM inbounds WHERE id = ?`, iid).Scan(&exists); err != nil {
			return err
		}
		if exists == 0 {
			return fmt.Errorf("入站不存在：%s", iid)
		}
		if err := tx.QueryRow(`SELECT COUNT(*) FROM proxy_chain_hops WHERE node_id = ? AND inbound_id = ?`,
			nodeID, iid).Scan(&exists); err != nil {
			return err
		}
		if exists > 0 {
			return fmt.Errorf("节点/入站已被代理链占用：%s/%s", nodeID, iid)
		}
		pubAddr := strings.TrimSpace(b.PublicAddress)
		pubPort := b.PublicPort
		if pubPort < 0 || pubPort > 65535 {
			return fmt.Errorf("入站 %s 的公网端口超出有效范围：%d", iid, pubPort)
		}
		if _, err := tx.Exec(
			`INSERT INTO node_inbounds (node_id, inbound_id, public_address, public_port, frp_enabled, frpc_config) VALUES (?, ?, ?, ?, ?, ?)`,
			nodeID, iid, pubAddr, pubPort, b.FRPEnabled, b.FRPCConfig,
		); err != nil {
			return fmt.Errorf("关联入站失败：%w", err)
		}
	}
	return tx.Commit()
}

// ListInboundsForNode returns attached inbound configs (without NAT overrides).
// Prefer ListNodeInboundAttachments when subscription NAT fields are needed.
func (s *Store) ListInboundsForNode(nodeID string) ([]InboundConfig, error) {
	atts, err := s.ListNodeInboundAttachments(nodeID)
	if err != nil {
		return nil, err
	}
	out := make([]InboundConfig, 0, len(atts))
	for _, a := range atts {
		out = append(out, a.EffectiveInbound())
	}
	return out, nil
}

// ListNodeInboundAttachments returns attached inbounds with per-inbound public host/port overrides.
func (s *Store) ListNodeInboundAttachments(nodeID string) ([]NodeInboundAttachment, error) {
	rows, err := s.db.Query(`
		SELECT i.id, i.name, i.protocol, i.params_json, i.enabled, i.created_at_unix, i.updated_at_unix,
			COALESCE(ni.public_address, ''), COALESCE(ni.public_port, 0), ni.frp_enabled, ni.frpc_config
		FROM inbounds i
		INNER JOIN node_inbounds ni ON ni.inbound_id = i.id
		WHERE ni.node_id = ?
		ORDER BY i.created_at_unix ASC`, nodeID)
	if err != nil {
		return nil, fmt.Errorf("查询节点入站关联失败：%w", err)
	}
	defer rows.Close()
	return scanNodeInboundAttachments(rows)
}

// ListAllNodeInboundAttachments returns attachments for every node in one
// query, grouped by node ID. Bulk callers (subscription rendering) use it to
// avoid per-node queries.
func (s *Store) ListAllNodeInboundAttachments() (map[string][]NodeInboundAttachment, error) {
	rows, err := s.db.Query(`
		SELECT ni.node_id, i.id, i.name, i.protocol, i.params_json, i.enabled, i.created_at_unix, i.updated_at_unix,
			COALESCE(ni.public_address, ''), COALESCE(ni.public_port, 0), ni.frp_enabled, ni.frpc_config
		FROM inbounds i
		INNER JOIN node_inbounds ni ON ni.inbound_id = i.id
		ORDER BY ni.node_id, i.created_at_unix ASC`)
	if err != nil {
		return nil, fmt.Errorf("查询全部节点入站关联失败：%w", err)
	}
	defer rows.Close()
	out := map[string][]NodeInboundAttachment{}
	for rows.Next() {
		var nodeID string
		var a NodeInboundAttachment
		var paramsJSON string
		var enabled, frpEnabled int
		if err := rows.Scan(
			&nodeID, &a.ID, &a.Name, &a.Protocol, &paramsJSON, &enabled, &a.CreatedAtUnix, &a.UpdatedAtUnix,
			&a.PublicAddress, &a.PublicPort, &frpEnabled, &a.FRPCConfig,
		); err != nil {
			return nil, fmt.Errorf("读取节点入站关联失败：%w", err)
		}
		a.Enabled = enabled != 0
		a.FRPEnabled = frpEnabled != 0
		a.Params = map[string]any{}
		if err := unmarshalJSON(paramsJSON, &a.Params); err != nil {
			return nil, fmt.Errorf("解析入站参数失败：%w", err)
		}
		out[nodeID] = append(out[nodeID], a)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

func scanNodeInboundAttachments(rows *sql.Rows) ([]NodeInboundAttachment, error) {
	var out []NodeInboundAttachment
	for rows.Next() {
		var a NodeInboundAttachment
		var paramsJSON string
		var enabled, frpEnabled int
		err := rows.Scan(
			&a.ID, &a.Name, &a.Protocol, &paramsJSON, &enabled, &a.CreatedAtUnix, &a.UpdatedAtUnix,
			&a.PublicAddress, &a.PublicPort, &frpEnabled, &a.FRPCConfig,
		)
		if err != nil {
			return nil, fmt.Errorf("读取节点入站关联失败：%w", err)
		}
		a.Enabled = enabled != 0
		a.FRPEnabled = frpEnabled != 0
		a.Params = map[string]any{}
		if err := unmarshalJSON(paramsJSON, &a.Params); err != nil {
			return nil, fmt.Errorf("解析入站参数失败：%w", err)
		}
		out = append(out, a)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if out == nil {
		out = []NodeInboundAttachment{}
	}
	return out, nil
}

// CountInboundsByNode returns node_id -> attached inbound count.
func (s *Store) CountInboundsByNode() (map[string]int, error) {
	rows, err := s.db.Query(`
		SELECT node_id, COUNT(*) FROM node_inbounds GROUP BY node_id`)
	if err != nil {
		return nil, fmt.Errorf("统计节点入站数量失败：%w", err)
	}
	defer rows.Close()
	out := map[string]int{}
	for rows.Next() {
		var id string
		var n int
		if err := rows.Scan(&id, &n); err != nil {
			return nil, err
		}
		out[id] = n
	}
	return out, rows.Err()
}

// NodeConfigFingerprint returns a cheap fingerprint of every table that feeds
// into a node's rendered sing-box config: the node row, its inbound
// attachments, proxy chains (global — hops on other nodes shape this node's
// outbounds), inbounds (global — chain hops reference them), and its managed
// TLS bindings/domains/certificates. Callers compare fingerprints to decide
// whether an expensive full config rebuild is needed.
func (s *Store) NodeConfigFingerprint(nodeID string) (string, error) {
	var (
		nodeUpdated                    int64
		ownInbounds, ownInboundUpdated int64
		chains, chainUpdated           int64
		inbounds, inboundUpdated       int64
		nodes, nodeUpdatedGlobal       int64
		tlsBindings, tlsUpdated        int64
		domains, domainUpdated         int64
		certs, certUpdated             int64
		attachmentKey                  string
	)
	err := s.db.QueryRow(`
		SELECT
			(SELECT COALESCE(MAX(updated_at_unix), 0) FROM nodes WHERE id = ?),
			(SELECT COUNT(*) FROM node_inbounds WHERE node_id = ?),
			(SELECT COALESCE(MAX(i.updated_at_unix), 0) FROM node_inbounds ni
				INNER JOIN inbounds i ON i.id = ni.inbound_id WHERE ni.node_id = ?),
			(SELECT COUNT(*) FROM proxy_chains),
			(SELECT COALESCE(MAX(updated_at_unix), 0) FROM proxy_chains),
			(SELECT COUNT(*) FROM inbounds),
			(SELECT COALESCE(MAX(updated_at_unix), 0) FROM inbounds),
			(SELECT COUNT(*) FROM nodes),
			(SELECT COALESCE(MAX(updated_at_unix), 0) FROM nodes),
			(SELECT COUNT(*) FROM node_inbound_tls_bindings WHERE node_id = ?),
			(SELECT COALESCE(MAX(updated_at_unix), 0) FROM node_inbound_tls_bindings WHERE node_id = ?),
			(SELECT COUNT(*) FROM managed_domains WHERE node_id = ?),
			(SELECT COALESCE(MAX(updated_at_unix), 0) FROM managed_domains WHERE node_id = ?),
			(SELECT COUNT(*) FROM protocol_certificates WHERE node_id = ?),
			(SELECT COALESCE(MAX(updated_at_unix), 0) FROM protocol_certificates WHERE node_id = ?),
			(SELECT COALESCE(GROUP_CONCAT(member, ','), '') FROM (
				SELECT ni.inbound_id || ':' || COALESCE(ni.public_address, '') || ':' ||
					COALESCE(ni.public_port, 0) || ':' || ni.frp_enabled || ':' || ni.frpc_config AS member
				FROM node_inbounds ni WHERE ni.node_id = ? ORDER BY ni.inbound_id
			))`,
		nodeID, nodeID, nodeID, nodeID, nodeID, nodeID, nodeID, nodeID, nodeID, nodeID,
	).Scan(
		&nodeUpdated, &ownInbounds, &ownInboundUpdated,
		&chains, &chainUpdated, &inbounds, &inboundUpdated,
		&nodes, &nodeUpdatedGlobal,
		&tlsBindings, &tlsUpdated, &domains, &domainUpdated, &certs, &certUpdated,
		&attachmentKey,
	)
	if err != nil {
		return "", fmt.Errorf("计算节点配置指纹失败：%w", err)
	}
	return fmt.Sprintf("%d:%d:%d:%d:%d:%d:%d:%d:%d:%d:%d:%d:%d:%d:%d|%s",
		nodeUpdated, ownInbounds, ownInboundUpdated,
		chains, chainUpdated, inbounds, inboundUpdated,
		nodes, nodeUpdatedGlobal,
		tlsBindings, tlsUpdated, domains, domainUpdated, certs, certUpdated,
		attachmentKey,
	), nil
}

// --- Tasks ---

func (s *Store) CreateTask(t *Task) error {
	if t == nil {
		return fmt.Errorf("任务不能为空")
	}
	if t.ID == "" {
		t.ID = newID()
	}
	now := nowUnix()
	if t.CreatedAtUnix == 0 {
		t.CreatedAtUnix = now
	}
	if t.UpdatedAtUnix == 0 {
		t.UpdatedAtUnix = now
	}
	if t.NodeIDs == nil {
		t.NodeIDs = []string{}
	}
	if t.Results == nil {
		t.Results = []TaskNodeResult{}
	}
	nodeIDsJSON, err := marshalJSON(t.NodeIDs)
	if err != nil {
		return fmt.Errorf("编码节点 ID 列表失败：%w", err)
	}
	resultsJSON, err := marshalJSON(t.Results)
	if err != nil {
		return fmt.Errorf("编码任务结果失败：%w", err)
	}
	_, err = s.db.Exec(`
		INSERT INTO tasks (id, type, status, node_ids_json, results_json, created_at_unix, updated_at_unix)
		VALUES (?, ?, ?, ?, ?, ?, ?)`,
		t.ID, t.Type, t.Status, nodeIDsJSON, resultsJSON, t.CreatedAtUnix, t.UpdatedAtUnix,
	)
	if err != nil {
		return fmt.Errorf("创建任务失败：%w", err)
	}
	return nil
}

func (s *Store) UpdateTask(t *Task) error {
	if t == nil || t.ID == "" {
		return fmt.Errorf("必须提供任务 ID")
	}
	t.UpdatedAtUnix = nowUnix()
	if t.NodeIDs == nil {
		t.NodeIDs = []string{}
	}
	if t.Results == nil {
		t.Results = []TaskNodeResult{}
	}
	nodeIDsJSON, err := marshalJSON(t.NodeIDs)
	if err != nil {
		return fmt.Errorf("编码节点 ID 列表失败：%w", err)
	}
	resultsJSON, err := marshalJSON(t.Results)
	if err != nil {
		return fmt.Errorf("编码任务结果失败：%w", err)
	}
	res, err := s.db.Exec(`
		UPDATE tasks SET type = ?, status = ?, node_ids_json = ?, results_json = ?, updated_at_unix = ?
		WHERE id = ?`,
		t.Type, t.Status, nodeIDsJSON, resultsJSON, t.UpdatedAtUnix, t.ID,
	)
	if err != nil {
		return fmt.Errorf("更新任务失败：%w", err)
	}
	rows, _ := res.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("任务不存在：%s", t.ID)
	}
	return nil
}

func scanTask(row interface {
	Scan(dest ...any) error
}) (*Task, error) {
	var t Task
	var nodeIDsJSON, resultsJSON string
	err := row.Scan(&t.ID, &t.Type, &t.Status, &nodeIDsJSON, &resultsJSON, &t.CreatedAtUnix, &t.UpdatedAtUnix)
	if err != nil {
		return nil, err
	}
	t.NodeIDs = []string{}
	t.Results = []TaskNodeResult{}
	if err := unmarshalJSON(nodeIDsJSON, &t.NodeIDs); err != nil {
		return nil, fmt.Errorf("解析节点 ID 列表失败：%w", err)
	}
	if err := unmarshalJSON(resultsJSON, &t.Results); err != nil {
		return nil, fmt.Errorf("解析任务结果失败：%w", err)
	}
	return &t, nil
}

const taskSelectCols = `id, type, status, node_ids_json, results_json, created_at_unix, updated_at_unix`

func (s *Store) GetTask(id string) (*Task, error) {
	row := s.db.QueryRow(`SELECT `+taskSelectCols+` FROM tasks WHERE id = ?`, id)
	t, err := scanTask(row)
	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("任务不存在：%s", id)
	}
	if err != nil {
		return nil, fmt.Errorf("读取任务失败：%w", err)
	}
	return t, nil
}

func (s *Store) ListTasks() ([]Task, error) {
	rows, err := s.db.Query(`SELECT ` + taskSelectCols + ` FROM tasks ORDER BY created_at_unix DESC`)
	if err != nil {
		return nil, fmt.Errorf("查询任务列表失败：%w", err)
	}
	defer rows.Close()

	var out []Task
	for rows.Next() {
		t, err := scanTask(rows)
		if err != nil {
			return nil, fmt.Errorf("读取任务列表失败：%w", err)
		}
		out = append(out, *t)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if out == nil {
		out = []Task{}
	}
	return out, nil
}

// --- Agent commands (uplink command queue) ---

const agentCommandCols = `id, node_id, type, payload_json, status, attempt, lease_expires_unix, result_json, error, created_at_unix, completed_at_unix, expires_at_unix`

func scanAgentCommand(row interface {
	Scan(dest ...any) error
}) (*AgentCommand, error) {
	var c AgentCommand
	err := row.Scan(&c.ID, &c.NodeID, &c.Type, &c.Payload, &c.Status, &c.Attempt,
		&c.LeaseExpiresUnix, &c.Result, &c.Error, &c.CreatedAtUnix, &c.CompletedAtUnix, &c.ExpiresAtUnix)
	if err != nil {
		return nil, err
	}
	return &c, nil
}

// CreateAgentCommand enqueues a pending command for a node.
func (s *Store) CreateAgentCommand(c *AgentCommand) error {
	if c == nil {
		return fmt.Errorf("命令不能为空")
	}
	if c.NodeID == "" {
		return fmt.Errorf("必须提供节点 ID")
	}
	if c.Type == "" {
		return fmt.Errorf("必须提供命令类型")
	}
	if c.ID == "" {
		c.ID = newID()
	}
	now := nowUnix()
	if c.CreatedAtUnix == 0 {
		c.CreatedAtUnix = now
	}
	if c.Status == "" {
		c.Status = AgentCommandPending
	}
	if c.Payload == "" {
		c.Payload = "{}"
	}
	if c.ExpiresAtUnix == 0 {
		c.ExpiresAtUnix = now + defaultCommandTTLSec
	}
	_, err := s.db.Exec(`
		INSERT INTO agent_commands (`+agentCommandCols+`)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		c.ID, c.NodeID, c.Type, c.Payload, c.Status, c.Attempt, c.LeaseExpiresUnix,
		c.Result, c.Error, c.CreatedAtUnix, c.CompletedAtUnix, c.ExpiresAtUnix,
	)
	if err != nil {
		return fmt.Errorf("创建节点命令失败：%w", err)
	}
	return nil
}

// defaultCommandTTLSec is how long a queued command stays valid before it is
// expired if the node never picks it up. defaultLeaseSec is the visibility
// timeout: after a node leases a command, it becomes re-deliverable if no
// result arrives before the lease expires.
const (
	defaultCommandTTLSec = 300
	defaultLeaseSec      = 60
)

// GetAgentCommand reads a single command by ID.
func (s *Store) GetAgentCommand(id string) (*AgentCommand, error) {
	row := s.db.QueryRow(`SELECT `+agentCommandCols+` FROM agent_commands WHERE id = ?`, id)
	c, err := scanAgentCommand(row)
	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("命令不存在：%s", id)
	}
	if err != nil {
		return nil, fmt.Errorf("读取命令失败：%w", err)
	}
	return c, nil
}

// LeaseAgentCommands atomically claims up to limit deliverable commands for a
// node and marks them leased with a fresh visibility timeout. A command is
// deliverable when it is pending, or leased with an expired lease (redelivery),
// and not past its TTL. Expired-by-TTL commands are swept to 'expired' first.
func (s *Store) LeaseAgentCommands(nodeID string, limit int, leaseSec int64) ([]AgentCommand, error) {
	if nodeID == "" {
		return nil, fmt.Errorf("必须提供节点 ID")
	}
	if limit <= 0 {
		limit = 16
	}
	if leaseSec <= 0 {
		leaseSec = defaultLeaseSec
	}
	s.mu.Lock()
	defer s.mu.Unlock()

	now := nowUnix()
	// Sweep TTL-expired commands that were never completed.
	if _, err := s.db.Exec(`
		UPDATE agent_commands SET status = ?, completed_at_unix = ?, error = ?
		WHERE node_id = ? AND status IN (?, ?) AND expires_at_unix > 0 AND expires_at_unix <= ?`,
		AgentCommandExpired, now, "命令超时未被节点执行", nodeID,
		AgentCommandPending, AgentCommandLeased, now,
	); err != nil {
		return nil, fmt.Errorf("清理过期命令失败：%w", err)
	}

	rows, err := s.db.Query(`
		SELECT `+agentCommandCols+` FROM agent_commands
		WHERE node_id = ? AND (
			status = ? OR (status = ? AND lease_expires_unix <= ?)
		)
		ORDER BY created_at_unix ASC
		LIMIT ?`,
		nodeID, AgentCommandPending, AgentCommandLeased, now, limit,
	)
	if err != nil {
		return nil, fmt.Errorf("查询待执行命令失败：%w", err)
	}
	var claimed []AgentCommand
	for rows.Next() {
		c, err := scanAgentCommand(rows)
		if err != nil {
			rows.Close()
			return nil, fmt.Errorf("读取待执行命令失败：%w", err)
		}
		claimed = append(claimed, *c)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return nil, err
	}

	lease := now + leaseSec
	for i := range claimed {
		c := &claimed[i]
		c.Status = AgentCommandLeased
		c.Attempt++
		c.LeaseExpiresUnix = lease
		if _, err := s.db.Exec(`
			UPDATE agent_commands SET status = ?, attempt = ?, lease_expires_unix = ?
			WHERE id = ?`,
			c.Status, c.Attempt, c.LeaseExpiresUnix, c.ID,
		); err != nil {
			return nil, fmt.Errorf("锁定命令失败：%w", err)
		}
	}
	if claimed == nil {
		claimed = []AgentCommand{}
	}
	return claimed, nil
}

// CompleteAgentCommand records a terminal result for a command. It is
// idempotent: once a command is succeeded/failed/expired it is not overwritten,
// so duplicate deliveries from at-least-once semantics are safe. Returns the
// stored command and whether this call actually applied the result.
func (s *Store) CompleteAgentCommand(id string, ok bool, result, errMsg string) (*AgentCommand, bool, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	c, err := s.GetAgentCommand(id)
	if err != nil {
		return nil, false, err
	}
	if c.Status == AgentCommandSucceeded || c.Status == AgentCommandFailed || c.Status == AgentCommandExpired {
		return c, false, nil
	}
	now := nowUnix()
	status := AgentCommandFailed
	if ok {
		status = AgentCommandSucceeded
	}
	if _, err := s.db.Exec(`
		UPDATE agent_commands SET status = ?, result_json = ?, error = ?, completed_at_unix = ?, lease_expires_unix = 0
		WHERE id = ?`,
		status, result, errMsg, now, id,
	); err != nil {
		return nil, false, fmt.Errorf("写入命令结果失败：%w", err)
	}
	c.Status = status
	c.Result = result
	c.Error = errMsg
	c.CompletedAtUnix = now
	c.LeaseExpiresUnix = 0
	return c, true, nil
}

// --- Settings ---

func (s *Store) GetSettings() (*Settings, error) {
	var st Settings
	var migrated int
	err := s.db.QueryRow(`
		SELECT admin_password_hash, default_agent_token, grpc_timeout_sec, max_concurrency,
			listen_addr, public_base_url, chain_probe_url, chain_probe_interval_sec,
			chain_probe_timeout_sec, chain_subscription_migrated, session_version,
			trusted_proxy_cidrs
		FROM settings WHERE id = 1`).Scan(
		&st.AdminPasswordHash, &st.DefaultAgentToken, &st.GRPCTimeoutSec, &st.MaxConcurrency,
		&st.ListenAddr, &st.PublicBaseURL, &st.ChainProbeURL, &st.ChainProbeIntervalSec,
		&st.ChainProbeTimeoutSec, &migrated, &st.SessionVersion, &st.TrustedProxyCIDRs,
	)
	if err != nil {
		return nil, fmt.Errorf("读取系统设置失败：%w", err)
	}
	st.ChainSubscriptionMigrated = migrated != 0
	return &st, nil
}

func (s *Store) SaveSettings(st *Settings) error {
	if st == nil {
		return fmt.Errorf("系统设置不能为空")
	}
	_, err := s.db.Exec(`
		UPDATE settings SET
			admin_password_hash = ?,
			default_agent_token = ?,
			grpc_timeout_sec = ?,
			max_concurrency = ?,
			listen_addr = ?,
			public_base_url = ?,
			chain_probe_url = ?,
			chain_probe_interval_sec = ?,
			chain_probe_timeout_sec = ?,
			chain_subscription_migrated = ?,
			trusted_proxy_cidrs = ?
		WHERE id = 1`,
		st.AdminPasswordHash, st.DefaultAgentToken, st.GRPCTimeoutSec, st.MaxConcurrency,
		st.ListenAddr, st.PublicBaseURL, st.ChainProbeURL, st.ChainProbeIntervalSec,
		st.ChainProbeTimeoutSec, boolToInt(st.ChainSubscriptionMigrated), st.TrustedProxyCIDRs,
	)
	if err != nil {
		return fmt.Errorf("保存系统设置失败：%w", err)
	}
	return nil
}

// BumpSessionVersion increments the session version, revoking all previously
// issued session tokens. Returns the new version.
func (s *Store) BumpSessionVersion() (int64, error) {
	if _, err := s.db.Exec(`UPDATE settings SET session_version = session_version + 1 WHERE id = 1`); err != nil {
		return 0, fmt.Errorf("递增会话版本失败：%w", err)
	}
	var version int64
	if err := s.db.QueryRow(`SELECT session_version FROM settings WHERE id = 1`).Scan(&version); err != nil {
		return 0, fmt.Errorf("读取会话版本失败：%w", err)
	}
	return version, nil
}

// MigrateSubscriptionsToChains switches subscriptions that currently expose
// local standalone endpoints to all enabled chains. It is intentionally
// one-shot and leaves external-only subscriptions untouched.
func (s *Store) MigrateSubscriptionsToChains() error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()
	var migrated int
	if err := tx.QueryRow(`SELECT chain_subscription_migrated FROM settings WHERE id = 1`).Scan(&migrated); err != nil {
		return err
	}
	if migrated != 0 {
		return nil
	}
	if _, err := tx.Exec(`
		UPDATE subscriptions
		SET include_standalone = 0, include_all_chains = 1, chain_ids_json = '[]',
			updated_at_unix = ?
		WHERE COALESCE(include_all_inbounds, 1) = 1
		   OR TRIM(inbound_ids_json) NOT IN ('', '[]', 'null')`, nowUnix()); err != nil {
		return err
	}
	if _, err := tx.Exec(`UPDATE settings SET chain_subscription_migrated = 1 WHERE id = 1`); err != nil {
		return err
	}
	return tx.Commit()
}

// --- Subscriptions ---

func (s *Store) CreateSubscription(sub *Subscription) error {
	if sub == nil {
		return fmt.Errorf("订阅不能为空")
	}
	if sub.ID == "" {
		sub.ID = newID()
	}
	if sub.Token == "" {
		return fmt.Errorf("必须提供令牌")
	}
	now := nowUnix()
	if sub.CreatedAtUnix == 0 {
		sub.CreatedAtUnix = now
	}
	sub.UpdatedAtUnix = now
	if sub.InboundIDs == nil {
		sub.InboundIDs = []string{}
	}
	if sub.IncludeAllInbounds {
		sub.InboundIDs = []string{}
	}
	if sub.ChainIDs == nil {
		sub.ChainIDs = []string{}
	}
	if sub.IncludeAllChains {
		sub.ChainIDs = []string{}
	}
	idsJSON, err := marshalJSON(sub.InboundIDs)
	if err != nil {
		return err
	}
	chainIDsJSON, err := marshalJSON(sub.ChainIDs)
	if err != nil {
		return err
	}
	_, err = s.db.Exec(`
		INSERT INTO subscriptions (
			id, name, format, token, inbound_ids_json, include_all_inbounds,
			include_standalone, chain_ids_json, include_all_chains,
			route_plan_id, enabled, disabled, created_at_unix, updated_at_unix
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		sub.ID, sub.Name, sub.Format, sub.Token, idsJSON, boolToInt(sub.IncludeAllInbounds),
		boolToInt(sub.IncludeStandalone), chainIDsJSON, boolToInt(sub.IncludeAllChains),
		sub.RoutePlanID, boolToInt(sub.Enabled), boolToInt(sub.Disabled), sub.CreatedAtUnix, sub.UpdatedAtUnix,
	)
	if err != nil {
		return fmt.Errorf("创建订阅失败：%w", err)
	}
	return nil
}

func (s *Store) UpdateSubscription(sub *Subscription) error {
	if sub == nil || sub.ID == "" {
		return fmt.Errorf("必须提供订阅 ID")
	}
	sub.UpdatedAtUnix = nowUnix()
	if sub.InboundIDs == nil {
		sub.InboundIDs = []string{}
	}
	if sub.IncludeAllInbounds {
		sub.InboundIDs = []string{}
	}
	if sub.ChainIDs == nil {
		sub.ChainIDs = []string{}
	}
	if sub.IncludeAllChains {
		sub.ChainIDs = []string{}
	}
	idsJSON, err := marshalJSON(sub.InboundIDs)
	if err != nil {
		return err
	}
	chainIDsJSON, err := marshalJSON(sub.ChainIDs)
	if err != nil {
		return err
	}
	res, err := s.db.Exec(`
		UPDATE subscriptions SET
			name=?, format=?, token=?, inbound_ids_json=?, include_all_inbounds=?,
			include_standalone=?, chain_ids_json=?, include_all_chains=?,
			route_plan_id=?, enabled=?, disabled=?, updated_at_unix=?
		WHERE id=?`,
		sub.Name, sub.Format, sub.Token, idsJSON, boolToInt(sub.IncludeAllInbounds),
		boolToInt(sub.IncludeStandalone), chainIDsJSON, boolToInt(sub.IncludeAllChains),
		sub.RoutePlanID, boolToInt(sub.Enabled), boolToInt(sub.Disabled), sub.UpdatedAtUnix, sub.ID,
	)
	if err != nil {
		return fmt.Errorf("更新订阅失败：%w", err)
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("订阅不存在：%s", sub.ID)
	}
	return nil
}

func (s *Store) DeleteSubscription(id string) error {
	res, err := s.db.Exec(`DELETE FROM subscriptions WHERE id = ?`, id)
	if err != nil {
		return fmt.Errorf("删除订阅失败：%w", err)
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("订阅不存在：%s", id)
	}
	return nil
}

const subscriptionSelectCols = `id, name, format, token, inbound_ids_json, COALESCE(include_all_inbounds, 1),
	include_standalone, chain_ids_json, include_all_chains,
	route_plan_id, enabled, disabled, created_at_unix, updated_at_unix`

func (s *Store) GetSubscription(id string) (*Subscription, error) {
	row := s.db.QueryRow(`SELECT `+subscriptionSelectCols+`
		FROM subscriptions WHERE id = ?`, id)
	return scanSubscription(row)
}

func (s *Store) GetSubscriptionByToken(token string) (*Subscription, error) {
	row := s.db.QueryRow(`SELECT `+subscriptionSelectCols+`
		FROM subscriptions WHERE token = ?`, token)
	sub, err := scanSubscription(row)
	if err != nil {
		return nil, err
	}
	return sub, nil
}

func (s *Store) ListSubscriptions() ([]Subscription, error) {
	rows, err := s.db.Query(`SELECT ` + subscriptionSelectCols + `
		FROM subscriptions ORDER BY created_at_unix ASC`)
	if err != nil {
		return nil, fmt.Errorf("查询订阅列表失败：%w", err)
	}
	defer rows.Close()
	var out []Subscription
	for rows.Next() {
		sub, err := scanSubscription(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *sub)
	}
	if out == nil {
		out = []Subscription{}
	}
	return out, rows.Err()
}

func scanSubscription(row interface {
	Scan(dest ...any) error
}) (*Subscription, error) {
	var sub Subscription
	var idsJSON, chainIDsJSON string
	var enabled, includeAll, includeStandalone, includeAllChains, disabled int
	err := row.Scan(
		&sub.ID, &sub.Name, &sub.Format, &sub.Token, &idsJSON, &includeAll,
		&includeStandalone, &chainIDsJSON, &includeAllChains,
		&sub.RoutePlanID, &enabled, &disabled, &sub.CreatedAtUnix, &sub.UpdatedAtUnix,
	)
	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("订阅不存在")
	}
	if err != nil {
		return nil, err
	}
	sub.Enabled = enabled != 0
	sub.Disabled = disabled != 0
	sub.IncludeAllInbounds = includeAll != 0
	sub.IncludeStandalone = includeStandalone != 0
	sub.IncludeAllChains = includeAllChains != 0
	sub.InboundIDs = []string{}
	if err := unmarshalJSON(idsJSON, &sub.InboundIDs); err != nil {
		return nil, fmt.Errorf("解析入站 ID 列表失败：%w", err)
	}
	sub.ChainIDs = []string{}
	if err := unmarshalJSON(chainIDsJSON, &sub.ChainIDs); err != nil {
		return nil, fmt.Errorf("解析代理链 ID 列表失败：%w", err)
	}
	if sub.InboundIDs == nil {
		sub.InboundIDs = []string{}
	}
	return &sub, nil
}

// --- External sources ---

func (s *Store) CreateExternalSource(src *ExternalSource) error {
	if src == nil {
		return fmt.Errorf("外部源不能为空")
	}
	if strings.TrimSpace(src.Name) == "" {
		return fmt.Errorf("必须提供名称")
	}
	if strings.TrimSpace(src.URL) == "" {
		return fmt.Errorf("必须提供 URL")
	}
	if src.ID == "" {
		src.ID = newID()
	}
	now := nowUnix()
	if src.CreatedAtUnix == 0 {
		src.CreatedAtUnix = now
	}
	src.UpdatedAtUnix = now
	if src.Headers == nil {
		src.Headers = map[string]string{}
	}
	headersJSON, err := marshalJSON(src.Headers)
	if err != nil {
		return err
	}
	_, err = s.db.Exec(`
		INSERT INTO external_sources (
			id, name, url, headers_json, enabled, refresh_interval_sec,
			last_fetch_unix, last_success_unix, last_error, content_type,
			cached_body, cached_proxy_count, created_at_unix, updated_at_unix
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		src.ID, src.Name, src.URL, headersJSON, boolToInt(src.Enabled), src.RefreshIntervalSec,
		src.LastFetchUnix, src.LastSuccessUnix, src.LastError, src.ContentType,
		src.CachedBody, src.CachedProxyCount, src.CreatedAtUnix, src.UpdatedAtUnix,
	)
	if err != nil {
		return fmt.Errorf("创建外部源失败：%w", err)
	}
	return nil
}

func (s *Store) UpdateExternalSource(src *ExternalSource) error {
	if src == nil || src.ID == "" {
		return fmt.Errorf("必须提供外部源 ID")
	}
	existing, err := s.GetExternalSource(src.ID)
	if err != nil {
		return err
	}
	if src.Headers == nil {
		src.Headers = map[string]string{}
	}
	fetchInputChanged := strings.TrimSpace(existing.URL) != strings.TrimSpace(src.URL) ||
		!maps.Equal(existing.Headers, src.Headers)
	src.UpdatedAtUnix = nowUnix()
	headersJSON, err := marshalJSON(src.Headers)
	if err != nil {
		return err
	}
	if fetchInputChanged {
		src.CachedBody = ""
		src.CachedProxyCount = 0
		src.ContentType = ""
		src.LastSuccessUnix = 0
		src.LastError = ""
		src.LastFetchUnix = 0
	} else {
		src.CachedBody = existing.CachedBody
		src.CachedProxyCount = existing.CachedProxyCount
		src.ContentType = existing.ContentType
		src.LastSuccessUnix = existing.LastSuccessUnix
		src.LastError = existing.LastError
		src.LastFetchUnix = existing.LastFetchUnix
	}
	res, err := s.db.Exec(`
		UPDATE external_sources SET
			name=?, url=?, headers_json=?, enabled=?, refresh_interval_sec=?,
			last_fetch_unix=?, last_success_unix=?, last_error=?, content_type=?,
			cached_body=?, cached_proxy_count=?, updated_at_unix=?
		WHERE id=?`,
		src.Name, src.URL, headersJSON, boolToInt(src.Enabled), src.RefreshIntervalSec,
		src.LastFetchUnix, src.LastSuccessUnix, src.LastError, src.ContentType,
		src.CachedBody, src.CachedProxyCount, src.UpdatedAtUnix, src.ID,
	)
	if err != nil {
		return fmt.Errorf("更新外部源失败：%w", err)
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("外部源不存在：%s", src.ID)
	}
	return nil
}

func (s *Store) DeleteExternalSource(id string) error {
	_, _ = s.db.Exec(`DELETE FROM subscription_external_sources WHERE external_source_id = ?`, id)
	res, err := s.db.Exec(`DELETE FROM external_sources WHERE id = ?`, id)
	if err != nil {
		return fmt.Errorf("删除外部源失败：%w", err)
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("外部源不存在：%s", id)
	}
	return nil
}

func (s *Store) GetExternalSource(id string) (*ExternalSource, error) {
	row := s.db.QueryRow(`
		SELECT id, name, url, headers_json, enabled, refresh_interval_sec,
			last_fetch_unix, last_success_unix, last_error, content_type,
			cached_body, cached_proxy_count, created_at_unix, updated_at_unix
		FROM external_sources WHERE id = ?`, id)
	return scanExternalSource(row)
}

// ListExternalSources returns sources without cached body (lighter list payloads).
func (s *Store) ListExternalSources() ([]ExternalSource, error) {
	rows, err := s.db.Query(`
		SELECT id, name, url, headers_json, enabled, refresh_interval_sec,
			last_fetch_unix, last_success_unix, last_error, content_type,
			'' AS cached_body, cached_proxy_count, created_at_unix, updated_at_unix
		FROM external_sources ORDER BY created_at_unix ASC`)
	if err != nil {
		return nil, fmt.Errorf("查询外部源列表失败：%w", err)
	}
	defer rows.Close()
	var out []ExternalSource
	for rows.Next() {
		src, err := scanExternalSource(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *src)
	}
	if out == nil {
		out = []ExternalSource{}
	}
	return out, rows.Err()
}

// SaveExternalSourceCache writes fetch outcome + optional successful body.
func (s *Store) SaveExternalSourceCache(id, body, contentType string, proxyCount int, fetchUnix, successUnix int64, lastErr string) error {
	if id == "" {
		return fmt.Errorf("必须提供外部源 ID")
	}
	res, err := s.db.Exec(`
		UPDATE external_sources SET
			last_fetch_unix=?, last_success_unix=?, last_error=?,
			content_type=?, cached_body=?, cached_proxy_count=?, updated_at_unix=?
		WHERE id=?`,
		fetchUnix, successUnix, lastErr, contentType, body, proxyCount, nowUnix(), id,
	)
	if err != nil {
		return fmt.Errorf("保存外部源缓存失败：%w", err)
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("外部源不存在：%s", id)
	}
	return nil
}

// SetSubscriptionExternalSources replaces attached external sources (order = index).
func (s *Store) SetSubscriptionExternalSources(subID string, sourceIDs []string) error {
	if subID == "" {
		return fmt.Errorf("必须提供订阅 ID")
	}
	if _, err := s.GetSubscription(subID); err != nil {
		return err
	}
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()
	if _, err := tx.Exec(`DELETE FROM subscription_external_sources WHERE subscription_id = ?`, subID); err != nil {
		return fmt.Errorf("清空订阅外部源关联失败：%w", err)
	}
	seen := map[string]bool{}
	for i, sid := range sourceIDs {
		sid = strings.TrimSpace(sid)
		if sid == "" || seen[sid] {
			continue
		}
		seen[sid] = true
		var one int
		if err := tx.QueryRow(`SELECT 1 FROM external_sources WHERE id = ?`, sid).Scan(&one); err != nil {
			if err == sql.ErrNoRows {
				return fmt.Errorf("外部源不存在：%s", sid)
			}
			return err
		}
		if _, err := tx.Exec(`
			INSERT INTO subscription_external_sources (subscription_id, external_source_id, sort_order)
			VALUES (?, ?, ?)`, subID, sid, i); err != nil {
			return fmt.Errorf("关联外部源失败：%w", err)
		}
	}
	return tx.Commit()
}

func (s *Store) ListExternalSourceIDsForSubscription(subID string) ([]string, error) {
	rows, err := s.db.Query(`
		SELECT external_source_id FROM subscription_external_sources
		WHERE subscription_id = ? ORDER BY sort_order ASC, external_source_id ASC`, subID)
	if err != nil {
		return nil, fmt.Errorf("查询订阅外部源 ID 失败：%w", err)
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	if out == nil {
		out = []string{}
	}
	return out, rows.Err()
}

// ListExternalSourcesForSubscription returns attached sources (with cache body) in join order.
func (s *Store) ListExternalSourcesForSubscription(subID string) ([]ExternalSource, error) {
	rows, err := s.db.Query(`
		SELECT e.id, e.name, e.url, e.headers_json, e.enabled, e.refresh_interval_sec,
			e.last_fetch_unix, e.last_success_unix, e.last_error, e.content_type,
			e.cached_body, e.cached_proxy_count, e.created_at_unix, e.updated_at_unix
		FROM subscription_external_sources j
		JOIN external_sources e ON e.id = j.external_source_id
		WHERE j.subscription_id = ?
		ORDER BY j.sort_order ASC, e.id ASC`, subID)
	if err != nil {
		return nil, fmt.Errorf("查询订阅外部源失败：%w", err)
	}
	defer rows.Close()
	var out []ExternalSource
	for rows.Next() {
		src, err := scanExternalSource(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *src)
	}
	if out == nil {
		out = []ExternalSource{}
	}
	return out, rows.Err()
}

func scanExternalSource(row interface {
	Scan(dest ...any) error
}) (*ExternalSource, error) {
	var src ExternalSource
	var headersJSON string
	var enabled int
	err := row.Scan(
		&src.ID, &src.Name, &src.URL, &headersJSON, &enabled, &src.RefreshIntervalSec,
		&src.LastFetchUnix, &src.LastSuccessUnix, &src.LastError, &src.ContentType,
		&src.CachedBody, &src.CachedProxyCount, &src.CreatedAtUnix, &src.UpdatedAtUnix,
	)
	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("外部源不存在")
	}
	if err != nil {
		return nil, err
	}
	src.Enabled = enabled != 0
	src.Headers = map[string]string{}
	if err := unmarshalJSON(headersJSON, &src.Headers); err != nil {
		return nil, fmt.Errorf("解析请求头失败：%w", err)
	}
	return &src, nil
}

// --- Proxy chains ---

func validateProxyChain(c *ProxyChain) error {
	if c == nil {
		return fmt.Errorf("代理链不能为空")
	}
	c.Name = strings.TrimSpace(c.Name)
	if c.Name == "" {
		return fmt.Errorf("必须提供代理链名称")
	}
	if len(c.Hops) < 2 || len(c.Hops) > 8 {
		return fmt.Errorf("代理链必须包含 2 到 8 个跳点")
	}
	nodes := map[string]bool{}
	for i := range c.Hops {
		h := &c.Hops[i]
		h.Position = i
		h.DialAddress = strings.TrimSpace(h.DialAddress)
		if h.NodeID == "" || h.InboundID == "" {
			return fmt.Errorf("第 %d 跳必须提供 node_id 和 inbound_id", i+1)
		}
		if nodes[h.NodeID] {
			return fmt.Errorf("节点 %s 在代理链中重复出现", h.NodeID)
		}
		nodes[h.NodeID] = true
		if h.DialPort < 0 || h.DialPort > 65535 {
			return fmt.Errorf("第 %d 跳的 dial_port 必须为 0 或 1 到 65535", i+1)
		}
	}
	return nil
}

func (s *Store) validateProxyChainRefs(tx *sql.Tx, c *ProxyChain) error {
	for i, h := range c.Hops {
		var exists int
		if err := tx.QueryRow(`SELECT COUNT(*) FROM nodes WHERE id = ?`, h.NodeID).Scan(&exists); err != nil {
			return err
		}
		if exists == 0 {
			return fmt.Errorf("第 %d 跳的节点不存在：%s", i+1, h.NodeID)
		}
		var enabled int
		if err := tx.QueryRow(`SELECT enabled FROM inbounds WHERE id = ?`, h.InboundID).Scan(&enabled); err != nil {
			if err == sql.ErrNoRows {
				return fmt.Errorf("第 %d 跳的入站不存在：%s", i+1, h.InboundID)
			}
			return err
		}
		if enabled == 0 {
			return fmt.Errorf("第 %d 跳的入站已禁用：%s", i+1, h.InboundID)
		}
		if err := tx.QueryRow(`SELECT COUNT(*) FROM node_inbounds WHERE node_id = ? AND inbound_id = ?`,
			h.NodeID, h.InboundID).Scan(&exists); err != nil {
			return err
		}
		if exists > 0 {
			return fmt.Errorf("第 %d 跳的节点/入站已经是独立绑定", i+1)
		}
		if err := tx.QueryRow(`SELECT COUNT(*) FROM proxy_chain_hops WHERE node_id = ? AND inbound_id = ? AND chain_id <> ?`,
			h.NodeID, h.InboundID, c.ID).Scan(&exists); err != nil {
			return err
		}
		if exists > 0 {
			return fmt.Errorf("第 %d 跳的节点/入站已被另一条代理链占用", i+1)
		}
	}
	return nil
}

func (s *Store) ValidateProxyChain(c *ProxyChain) error {
	if err := validateProxyChain(c); err != nil {
		return err
	}
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()
	if err := s.validateProxyChainRefs(tx, c); err != nil {
		return err
	}
	var exists int
	if err := tx.QueryRow(`SELECT COUNT(*) FROM proxy_chains WHERE name = ? COLLATE NOCASE AND id <> ?`,
		c.Name, c.ID).Scan(&exists); err != nil {
		return err
	}
	if exists > 0 {
		return fmt.Errorf("代理链名称已存在：%s", c.Name)
	}
	return nil
}

func insertProxyChainHops(tx *sql.Tx, c *ProxyChain) error {
	for i, h := range c.Hops {
		if _, err := tx.Exec(`
			INSERT INTO proxy_chain_hops
				(chain_id, position, node_id, inbound_id, dial_address, dial_port, tls_skip_verify)
			VALUES (?, ?, ?, ?, ?, ?, ?)`,
			c.ID, i, h.NodeID, h.InboundID, h.DialAddress, h.DialPort, boolToInt(h.TLSSkipVerify)); err != nil {
			return fmt.Errorf("保存代理链第 %d 跳失败：%w", i+1, err)
		}
	}
	return nil
}

func (s *Store) CreateProxyChain(c *ProxyChain) error {
	if err := validateProxyChain(c); err != nil {
		return err
	}
	if c.ID == "" {
		c.ID = newID()
	}
	now := nowUnix()
	c.CreatedAtUnix, c.UpdatedAtUnix = now, now
	c.Enabled = false
	c.State = "disabled"
	c.FailedHopIndex = -1
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()
	if err := s.validateProxyChainRefs(tx, c); err != nil {
		return err
	}
	if _, err := tx.Exec(`
		INSERT INTO proxy_chains
			(id, name, enabled, state, failed_hop_index, created_at_unix, updated_at_unix)
		VALUES (?, ?, 0, 'disabled', -1, ?, ?)`, c.ID, c.Name, now, now); err != nil {
		return fmt.Errorf("创建代理链失败：%w", err)
	}
	if err := insertProxyChainHops(tx, c); err != nil {
		return err
	}
	return tx.Commit()
}

// UpdateProxyChain replaces metadata and ordered hops. Runtime fields are
// preserved unless supplied by SetProxyChainRuntime.
func (s *Store) UpdateProxyChain(c *ProxyChain) error {
	if err := validateProxyChain(c); err != nil {
		return err
	}
	existing, err := s.GetProxyChain(c.ID)
	if err != nil {
		return err
	}
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()
	if err := s.validateProxyChainRefs(tx, c); err != nil {
		return err
	}
	if _, err := tx.Exec(`DELETE FROM proxy_chain_hops WHERE chain_id = ?`, c.ID); err != nil {
		return err
	}
	if err := insertProxyChainHops(tx, c); err != nil {
		return err
	}
	now := nowUnix()
	res, err := tx.Exec(`UPDATE proxy_chains SET name = ?, enabled = ?, state = ?, updated_at_unix = ? WHERE id = ?`,
		c.Name, boolToInt(c.Enabled), firstNonEmptyString(c.State, existing.State), now, c.ID)
	if err != nil {
		return fmt.Errorf("更新代理链失败：%w", err)
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return fmt.Errorf("代理链不存在：%s", c.ID)
	}
	c.CreatedAtUnix = existing.CreatedAtUnix
	c.UpdatedAtUnix = now
	return tx.Commit()
}

func firstNonEmptyString(values ...string) string {
	for _, value := range values {
		if value != "" {
			return value
		}
	}
	return ""
}

func scanProxyChain(row interface{ Scan(dest ...any) error }) (*ProxyChain, error) {
	var c ProxyChain
	var enabled int
	err := row.Scan(
		&c.ID, &c.Name, &enabled, &c.State,
		&c.LastDeployUnix, &c.LastDeployError,
		&c.LastProbeUnix, &c.LastProbeDelayMS, &c.LastProbeError, &c.FailedHopIndex,
		&c.CreatedAtUnix, &c.UpdatedAtUnix,
	)
	if err != nil {
		return nil, err
	}
	c.Enabled = enabled != 0
	c.Hops = []ProxyChainHop{}
	return &c, nil
}

const proxyChainSelectCols = `id, name, enabled, state,
	last_deploy_unix, last_deploy_error,
	last_probe_unix, last_probe_delay_ms, last_probe_error, failed_hop_index,
	created_at_unix, updated_at_unix`

func (s *Store) loadProxyChainHops(c *ProxyChain) error {
	rows, err := s.db.Query(`
		SELECT chain_id, position, node_id, inbound_id, dial_address, dial_port, tls_skip_verify
		FROM proxy_chain_hops WHERE chain_id = ? ORDER BY position`, c.ID)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var h ProxyChainHop
		var skip int
		if err := rows.Scan(&h.ChainID, &h.Position, &h.NodeID, &h.InboundID,
			&h.DialAddress, &h.DialPort, &skip); err != nil {
			return err
		}
		h.TLSSkipVerify = skip != 0
		c.Hops = append(c.Hops, h)
	}
	return rows.Err()
}

func (s *Store) GetProxyChain(id string) (*ProxyChain, error) {
	c, err := scanProxyChain(s.db.QueryRow(`SELECT `+proxyChainSelectCols+` FROM proxy_chains WHERE id = ?`, id))
	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("代理链不存在：%s", id)
	}
	if err != nil {
		return nil, fmt.Errorf("读取代理链失败：%w", err)
	}
	if err := s.loadProxyChainHops(c); err != nil {
		return nil, fmt.Errorf("加载代理链跳点失败：%w", err)
	}
	return c, nil
}

func (s *Store) ListProxyChains() ([]ProxyChain, error) {
	rows, err := s.db.Query(`SELECT ` + proxyChainSelectCols + ` FROM proxy_chains ORDER BY created_at_unix`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []ProxyChain
	for rows.Next() {
		c, err := scanProxyChain(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *c)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	for i := range out {
		if err := s.loadProxyChainHops(&out[i]); err != nil {
			return nil, err
		}
	}
	if out == nil {
		out = []ProxyChain{}
	}
	return out, nil
}

func (s *Store) SetProxyChainRuntime(id string, enabled bool, state, deployErr string) error {
	now := nowUnix()
	res, err := s.db.Exec(`
		UPDATE proxy_chains
		SET enabled = ?, state = ?, last_deploy_unix = ?, last_deploy_error = ?, updated_at_unix = ?
		WHERE id = ?`, boolToInt(enabled), state, now, deployErr, now, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return fmt.Errorf("代理链不存在：%s", id)
	}
	return nil
}

func (s *Store) SetProxyChainProbe(id string, ok bool, delayMS int, message string, failedHop int) error {
	state := "degraded"
	if ok {
		state = "healthy"
		message = ""
		failedHop = -1
	}
	now := nowUnix()
	_, err := s.db.Exec(`
		UPDATE proxy_chains
		SET state = ?, last_probe_unix = ?, last_probe_delay_ms = ?,
			last_probe_error = ?, failed_hop_index = ?, updated_at_unix = ?
		WHERE id = ? AND enabled = 1`,
		state, now, delayMS, message, failedHop, now, id)
	return err
}

func (s *Store) DeleteProxyChain(id string) error {
	var enabled int
	if err := s.db.QueryRow(`SELECT enabled FROM proxy_chains WHERE id = ?`, id).Scan(&enabled); err != nil {
		if err == sql.ErrNoRows {
			return fmt.Errorf("代理链不存在：%s", id)
		}
		return err
	}
	if enabled != 0 {
		return fmt.Errorf("删除代理链前请先将其禁用")
	}
	res, err := s.db.Exec(`DELETE FROM proxy_chains WHERE id = ?`, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return fmt.Errorf("代理链不存在：%s", id)
	}
	return nil
}

func (s *Store) InboundUsedByEnabledChain(inboundID string) (bool, error) {
	var n int
	err := s.db.QueryRow(`
		SELECT COUNT(*) FROM proxy_chain_hops h
		JOIN proxy_chains c ON c.id = h.chain_id
		WHERE h.inbound_id = ? AND c.enabled = 1`, inboundID).Scan(&n)
	return n > 0, err
}

func (s *Store) InboundUsedByAnyChain(inboundID string) (bool, error) {
	var n int
	err := s.db.QueryRow(`SELECT COUNT(*) FROM proxy_chain_hops WHERE inbound_id = ?`, inboundID).Scan(&n)
	return n > 0, err
}

// --- Snapshots ---

func (s *Store) SaveSnapshot(snap *ConfigSnapshot) error {
	if snap == nil {
		return fmt.Errorf("配置快照不能为空")
	}
	if snap.ID == "" {
		snap.ID = newID()
	}
	if snap.CreatedAtUnix == 0 {
		snap.CreatedAtUnix = nowUnix()
	}
	_, err := s.db.Exec(`
		INSERT INTO config_snapshots (id, node_id, config_json, config_hash, task_id, created_at_unix)
		VALUES (?, ?, ?, ?, ?, ?)`,
		snap.ID, snap.NodeID, snap.ConfigJSON, snap.ConfigHash, snap.TaskID, snap.CreatedAtUnix,
	)
	if err != nil {
		return fmt.Errorf("保存配置快照失败：%w", err)
	}
	return nil
}

func (s *Store) LatestSnapshot(nodeID string) (*ConfigSnapshot, error) {
	var snap ConfigSnapshot
	err := s.db.QueryRow(`
		SELECT id, node_id, config_json, config_hash, task_id, created_at_unix
		FROM config_snapshots
		WHERE node_id = ?
		ORDER BY created_at_unix DESC
		LIMIT 1`, nodeID).Scan(
		&snap.ID, &snap.NodeID, &snap.ConfigJSON, &snap.ConfigHash, &snap.TaskID, &snap.CreatedAtUnix,
	)
	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("未找到节点 %s 的配置快照", nodeID)
	}
	if err != nil {
		return nil, fmt.Errorf("读取最新配置快照失败：%w", err)
	}
	return &snap, nil
}
